In [1]:
import glob
from PIL import Image
import os
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import requests
import json

In [2]:
#display all columns (not just first and last 5)
pd.options.display.max_columns = None

In [3]:
data = requests.get('https://fantasy.premierleague.com/api/bootstrap-static/')
data = json.loads(data.content)

for key in data:
    print (key)

chips
events
game_settings
game_config
phases
teams
total_players
element_stats
element_types
elements

# Teams

In [4]:
len(data['teams'])

20

In [5]:
team_df = pd.DataFrame(data['teams'])
team_df.head()

,code,draw,form,id,loss,name,played,points,position,short_name,strength,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,1,ARS,4,None,False,0,1320,1325,1350,1350,1290,1300,1
1,7,0,None,2,0,Aston Villa,0,0,13,AVL,3,None,False,0,1125,1250,1110,1200,1140,1300,2
2,90,0,None,3,0,Burnley,0,0,18,BUR,2,None,False,0,1050,1050,1050,1050,1050,1050,43
3,91,0,None,4,0,Bournemouth,0,0,4,BOU,3,None,False,0,1150,1180,1100,1160,1200,1200,127
4,94,0,None,5,0,Brentford,0,0,16,BRE,3,None,False,0,1120,1185,1080,1080,1160,1290,130

# Players Season Cumulative Stats

In [6]:
player_season_df = pd.DataFrame(data['elements'])
player_season_df.sort_values('minutes', ascending=False).head()

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,removed,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,region,team_join_date,birth_date,has_temporary_code,opta_code,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,expected_goals_per_90,saves_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,goals_conceded_per_90,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,defensive_contribution_per_90
0,True,True,NaN,NaN,154561,1,-1,2,-2,1,1,4.5,4.5,6,David,4.0,1,False,,None,57,154561.jpg,4.9,False,Raya Martín,27.8,False,None,a,1,3,34,1560932,104357,678817,29659,0.7,6.0,Raya,200.0,2024-07-04,1995-09-15,False,p154561,630,0,0,4,3,0,0,0,1,0,15,3,146,135.8,10.0,0.0,14.5,4,61,0,0,7,0.00,0.04,0.04,4.40,67,11,321,8,726,85,194,11,NaN,,NaN,,NaN,,0.00,2.14,0.01,0.01,0.63,0.43,121,1,66,3,42,5,12,2,1.0,0.57,0.00
327,True,True,NaN,NaN,232928,0,0,0,0,0,3,3.7,4.2,1,James,4.2,303,False,,None,50,232928.jpg,4.7,False,Garner,1.0,False,None,a,9,11,33,139351,7311,44437,6055,0.8,6.6,Garner,241.0,2022-09-01,2001-03-13,False,p232928,630,1,1,2,7,0,0,0,2,0,0,5,166,186.8,149.9,68.0,40.5,35,29,18,82,7,0.55,1.05,1.60,9.87,21,10,25,22,82,50,17,13,3.0,,3.0,,NaN,,0.08,0.00,0.15,0.23,1.41,1.00,265,163,54,24,46,16,182,62,1.0,0.29,11.71
525,True,True,NaN,NaN,78916,1,-1,1,-1,1,2,7.0,7.0,11,Dan,6.5,476,True,,None,51,78916.jpg,6.1,False,Burn,8.1,False,None,a,15,4,43,679011,115638,218627,11404,1.3,8.4,Burn,241.0,2022-01-31,1992-05-09,False,p78916,630,0,1,5,5,0,0,0,2,0,0,4,134,128.6,29.9,33.0,19.2,49,24,9,58,7,0.05,0.13,0.18,4.98,76,35,206,57,178,42,146,46,NaN,,NaN,,NaN,,0.01,0.00,0.02,0.03,0.71,0.71,233,33,7,3,12,6,48,14,1.0,0.71,8.29
280,True,True,NaN,NaN,209036,0,0,3,-3,1,2,5.8,5.8,3,Marc,5.8,260,True,,None,48,209036.jpg,6.6,False,Guéhi,30.8,False,None,a,8,31,46,2582124,123051,461793,19695,1.2,9.6,Guéhi,241.0,2021-07-18,2000-07-13,False,p209036,630,1,2,3,5,0,0,0,0,0,0,3,154,180.4,41.2,76.0,29.8,42,24,15,57,7,0.59,0.57,1.16,8.85,24,8,168,42,72,8,59,12,NaN,,NaN,,NaN,,0.08,0.00,0.08,0.16,1.26,0.71,369,62,15,6,7,3,9,2,1.0,0.43,8.14
415,True,True,NaN,NaN,97032,0,0,1,-1,0,2,4.8,4.3,1,Virgil,3.8,373,False,,None,61,97032.jpg,4.1,False,van Dijk,28.0,False,None,a,12,14,29,1271520,26441,1010644,112667,0.6,4.8,Virgil,152.0,2018-01-01,1991-07-08,False,p97032,630,0,0,2,9,0,0,0,1,0,0,4,108,219.8,26.4,29.0,27.5,76,16,3,79,7,0.18,0.12,0.30,7.87,5,2,230,70,196,48,69,16,NaN,,3.0,,NaN,,0.03,0.00,0.02,0.05,1.12,1.29,83,2,75,31,74,35,11,4,1.0,0.29,11.29

In [7]:
player_season_df.query('team==3')

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,removed,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,region,team_join_date,birth_date,has_temporary_code,opta_code,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,expected_goals_per_90,saves_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,goals_conceded_per_90,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,defensive_contribution_per_90
77,True,True,NaN,NaN,518030,0,0,-1,1,0,1,0.0,-0.5,0,Max,0.0,183,False,,None,44,518030.jpg,0.0,False,Weiß,0.1,False,None,a,3,90,0,2874,117,9607,292,0.0,0.0,Weiss,80.0,2025-06-25,2004-06-15,False,p518030,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,568,80,557,69,533,60,570,80,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,566,35,545,78,574,80,435,67,0.00,0.00,0.00
78,True,False,0.0,0.0,489571,0,0,0,0,0,1,0.0,0.0,0,Etienne,0.0,184,False,has joined FC Fredericia permanently.,2025-09-02T12:51:25.510909Z,40,489571.jpg,0.0,False,Green,0.3,False,None,u,3,90,0,4943,0,22320,811,0.0,0.0,Green,241.0,2024-08-07,2000-07-19,False,p489571,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,498,64,482,49,449,38,500,64,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,667,72,468,61,503,64,323,48,0.00,0.00,0.00
79,True,True,NaN,NaN,51943,0,0,0,0,0,1,0.0,-0.5,0,Václav,0.0,185,False,,None,40,51943.jpg,0.0,False,Hladký,0.2,False,None,a,3,90,0,4696,127,8903,356,0.0,0.0,Hladký,57.0,2024-07-19,1990-11-14,False,p51943,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,455,34,435,17,403,6,456,34,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,610,40,423,31,459,34,380,61,0.00,0.00,0.00
80,True,True,50.0,0.0,192290,0,0,-1,1,0,2,0.0,0.0,0,Connor,0.0,186,False,Knee injury - 50% chance of playing,2025-08-22T12:30:06.986449Z,44,192290.jpg,0.0,False,Roberts,0.0,False,None,d,3,90,0,723,6,7173,116,0.0,0.0,Roberts,244.0,2021-08-31,1995-09-23,False,p192290,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,544,221,532,221,503,213,546,221,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,517,122,518,215,548,220,598,210,0.00,0.00,0.00
81,True,True,NaN,NaN,58621,-1,1,-1,1,0,2,1.0,0.5,1,Kyle,1.0,187,False,,None,44,58621.jpg,1.6,False,Walker,1.5,False,None,a,3,90,11,64104,2654,120760,5408,0.2,2.5,Walker,241.0,2025-07-05,1990-05-28,False,p58621,630,0,0,1,15,0,0,0,2,0,0,0,19,89.8,16.4,14.0,12.1,31,33,11,42,7,0.12,0.19,0.31,13.67,139,62,275,92,267,83,223,78,NaN,,NaN,,NaN,,0.02,0.00,0.03,0.05,1.95,2.14,501,109,263,94,304,106,150,56,1.00,0.14,6.00
82,True,True,NaN,NaN,247245,0,0,-1,1,0,2,0.0,-0.5,0,Hannes,0.0,188,False,,None,39,247245.jpg,0.0,False,Delcroix,0.3,False,None,a,3,90,0,9353,335,17599,622,0.0,0.0,Delcroix,21.0,2023-08-22,1999-02-28,False,p247245,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,427,153,406,149,374,139,428,152,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,716,220,394,141,431,152,327,117,0.00,0.00,0.00
83,True,False,0.0,0.0,461567,0,0,0,0,0,2,0.0,0.0,0,Owen,0.0,189,False,Has joined Stockport County on loan for the re...,2025-08-11T01:08:30.737822Z,40,461567.jpg,0.0,False,Dodgson,0.0,False,None,u,3,90,0,0,0,1985,37,0.0,0.0,Dodgson,241.0,2021-08-20,2003-03-19,False,p461567,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,488,189,472,188,439,177,490,189,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,653,178,458,180,493,189,669,228,0.00,0.00,0.00
84,True,True,NaN,NaN,478969,0,0,0,0,0,2,1.5,1.0,0,Hjalmar,1.5,190,False,,None,40,478969.jpg,3.2,False,Ekdal,1.4,False,None,a,3,90,19,205281,1152,79719,5318,0.4,4.8,Ekdal,206.0,2023-01-21,1998-10-21,False,p478969,532,0,0,1,12,0,0,0,0,0,0,1,44,130.2,26.4,61.0,21.7,52,14,8,60,6,0.15,0.16,0.31,11.24,72,32,229,69,98,16,121,38,NaN,,NaN,,NaN,,0.03,0.00,0.03,0.06,1.90,2.03,664,183,219,80,129,52,154,58,1.02,0.17,10.15
85,True,True,NaN,NaN,477717,0,0,0,0,0,2,1.8,1.3,1,Maxime,1.8,191,False,,None,40,477717.jpg,2.1,False,Estève,13.6,False,None,a,3,90,15,401808,7257,903192,41980,0.4,3.8,Estève,73.0,2024-06-14,2002-05-26,False,p477717,622,0,0,1,15,2,0,0,0,0,0,0,35,135.6,14.4,30.0,18.1,60,15,7,67,7,0.19,0.02,0.21,13.56,68,28,287,95,186,45,153,49,NaN,,NaN,,NaN,,0.03,0.00,0.00,0.03,1.96,2.17,663,182,194,69,245,85,27,10,1.01,0.14,9.69
86,True,True,NaN,NaN,494960,0,0,0,0,0,2,3.2,2.7,4,Quilindschy,3.2,192,False,,None,40,494960.jpg,3.0,False,Hartman,0.5,False,None,a,3,90,21,36837,2958,36195,1557,0.8,5.2,Hartman,152.0,2025-06-26,2001-11-14,False,p494960,627,0,2,1,13,0,0,0,1,0,0,0,68,154.8,122.5,29.0,30.6,37,15,14,51,7,0.13,0.69,0.82,13.05,46,19,41,8,190,47,52,10,2.0,,NaN,,NaN,,0.02,0.00,0.10,0.12,1.87,1.87,672,187,100,41,141,56,233,87,1.00,0.14,7.32
87,True,True,100.0,100.0,461188,0,0,0,0,0,2,0.0,-0.5,0,Bashir,0.0,193,False,,2025-08-10T22:00:04.557380Z,40,461188.jpg,0.0,False,Humphreys,0.1,False,None,a,3,90,0,1676,75,3392,192,0.0,0.0,Humphreys,241.0,2025-07-01,2003-03-15,False,p461188,2,0,0,0,2,0,0,0,0,0,0,0,-5,0.2,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.62,419,147,469,186,436,175,487,187,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,27.90,90.00,650,176,455,178,490,187,544,197,0.00,0.00,0.00
88,True,True,0.0,0.0,241231,0,0,0,0,0,2,0.0,0.0,0,Jordan,0.0,194,False,Hamstring injury - Unknown return date,2025-08-22T12:30:07.019474Z,40,241231.jpg,0.0,False,Beyer,0.1,False,None,i,3,90,0,860,12,11779,249,0.0,0.0,Jordan,80.0,2023-07-01,2000-05-19,False,p241231,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,479,184,462,182,429,171,480,183,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,640,169,447,173,483,183,493,180,0.00,0.00,0.00
89,True,True,NaN,NaN,549329,0,0,-1,1,0,2,0.0,-0.5,0,Lucas,0.0,195,False,,None,39,549329.jpg,0.0,False,Pires Silva,0.2,False,None,a,3,90,0,8766,175,10331,466,0.0,0.0,Lucas Pires,30.0,2024-07-16,2001-03-24,False,p549329,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,444,169,423,165,391,155,445,168,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,733,236,411,157,448,168,378,137,0.00,0.00,0.00
90,True,False,0.0,0.0,450072,0,0,0,0,0,2,0.0,0.0,0,Shurandy,0.0,196,False,Has joined Sparta Rotterdam on loan for the re...,2025-08-19T13:36:42.853472Z,40,450072.jpg,0.0,False,Sambo,0.1,False,None,u,3,90,0,202,0,8038,120,0.0,0.0,Sambo,152.0,2024-06-28,2001-08-19,False,p450072,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,485,187,468,185,435,174,486,186,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,649,175,454,177,489,186,560,204,0.00,0.00,0.00
91,True,True,NaN,NaN,519895,0,0,0,0,0,2,0.0,-0.5,0,Oliver,0.0,197,False,,None,40,519895.jpg,1.0,False,Sonne,0.1,False,None,a,3,90,3,4126,133,7835,335,0.0,0.8,Sonne,169.0,2025-01-01,2000-11-10,False,p519895,102,0,0,0,4,0,0,0,0,0,0,0,-2,7.6,16.4,6.0,3.0,1,3,1,2,1,0.03,0.08,0.11,3.31,379,140,274,91,315,109,367,128,NaN,,NaN,,NaN,,0.03,0.00,0.07,0.10,2.92,3.53,682,194,481,190,347,123,420,156,0.88,0.00,1.76
92,True,True,100.0,100.0,180804,0,0,-1,1,0,2,0.2,-0.3,1,Axel,0.2,198,False,,2025-08-22T12:30:07.036752Z,39,180804.jpg,1.0,False,Tuanzebe,1.8,False,None,a,3,90,1,86500,2964,140189,4314,0.1,0.3,Tuanzebe,50.0,2025-07-01,1997-11-14,False,p180804,90,0,0,0,2,0,0,0,0,0,0,0,6,17.6,0.9,0.0,1.9,4,4,3,7,1,0.00,0.01,0.01,1.37,341,127,372,132,368,134,382,133,NaN,,NaN,,NaN,,0.00,0.00,0.01,0.01,1.37,2.00,710,215,348,118,341,117,143,55,1.00,0.00,7.00
93,True,True,NaN,NaN,208912,0,0,-1,1,0,2,0.5,0.0,1,Joe,0.5,199,False,,None,39,208912.jpg,1.0,False,Worrall,0.2,False,None,a,3,90,4,11763,3423,7667,682,0.1,1.0,Worrall,241.0,2024-08-23,1997-01-10,False,p208912,19,0,0,0,2,0,0,0,0,0,0,0,9,11.2,0.3,0.0,1.2,5,1,1,6,0,0.00,0.00,0.00,2.17,365,137,390,142,369,135,394,140,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,10.28,9.47,711,216,322,110,342,118,360,129,0.00,0.00,28.42
94,True,True,75.0,NaN,444180,0,0,2,-2,2,3,3.8,4.5,1,Jaidon,5.0,200,True,Knock - 75% chance of playing,2025-10-07T11:30:07.662899Z,57,444180.jpg,5.9,False,Anthony,6.9,False,None,d,3,90,41,902123,99129,142297,27480,0.9,7.2,Anthony,241.0,2025-07-01,1999-12-01,False,p444180,587,4,1,2,11,0,0,0,2,0,0,5,144,219.0,100.4,174.0,49.4,14,29,12,55,7,2.16,0.62,2.78,11.73,6,3,60,46,13,6,10,8,3.0,,1.0,,NaN,,0.33,0.00,0.10,0.43,1.80,1.69,125,82,28,13,20,6,59,18,1.07,0.31,8.43
95,True,False,0.0,0.0,183751,0,0,-1,1,0,3,0.0,0.0,0,Manuel,0.0,201,False,has joined Swansea City on loan for the rest o...,2025-09-22T21:45:34.872207Z,54,183751.jpg,0.0,False,Benson Hedilazio,0.0,False,None,u,3,90,0,1070,0,2626,108,0.0,0.0,Benson,6.0,2022-08-04,1997-03-28,False,p183751,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,714,311,713,312,708,312,715,312,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,170,105,704,306,715,312,653,273,0.00,0.00,0.00
96,True,True,100.0,100.0,179458,0,0,-2,2,0,3,0.5,0.0,1,Jacob,0.5,202,False,,2025-09-14T22:00:08.065375Z,53,179458.jpg,2.2,False,Bruun Larsen,0.0,False,None,a,3,90,11,1825,91,4022,99,0.1,2.1,Bruun Larsen,58.0,2025-07-11,1998-09-19,False,p179458,235,0,1,1,7,0,0,0,0,0,0,0,31,33.2,31.2,20.0,8.3,6,8,1,15,2,0.05,0.34,0.39,5.43,281,128,201,128,234,129,276,137,NaN,,NaN,,2.0,,0.02,0.00,0.13,0.15,2.08,2.68,204,129,337,165,237,112,623,254,0.77,0.38,5.74
97,True,True,NaN,NaN,578614,0,0,-2,2,0,3,0.0,-0.5,0,Enock,0.0,203,False,,None,48,578614.jpg,0.0,False,Agyei,0.0,False,None,a,3,90,0,1169,81,3958,159,0.0,0.0,Boateng,21.0,2023-01-30,2005-01-13,False,p578614,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,667,281,661,282,642,274,668,282,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,384,240,647,269,667,281,590,229,0.00,0.00,0.00
98,True,False,0.0,0.0,250735,0,0,-1,1,0,3,0.0,0.0,0,Darko,0.0,204,False,has joined Kocaelispor permanently.,2025-09-02T12:51:25.524903Z,49,250735.jpg,0.0,False,Churlinov,0.0,False,None,u,3,90,0,160,0,1808,24,0.0,0.0,Churlinov,NaN,2022-08-19,2000-07-11,False,p250735,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,679,288,674,289,658,283,680,289,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,333,207,661,278,679,288,675,287,0.00,0.00,0.00
99,True,True,NaN,NaN,172567,0,0,0,0,1,3,4.2,3.7,6,Josh,4.2,205,False,,None,50,172567.jpg,5.3,False,Cullen,2.0,False,None,a,3,90,37,323466,11155,149630,8394,0.8,7.4,Cullen,104.0,2022-07-12,1996-04-07,False,p172567,590,1,1,2,12,1,0,0,0,0,0,5,150,189.2,107.4,28.0,32.5,38,33,15,86,7,0.18,0.59,0.77,11.65,17,7,56,43,198,116,43,29,1.0,,NaN,,NaN,,0.03,0.00,0.09,0.12,1.78,1.83,251,153,53,23,30,10,137,48,1.07,0.31,13.12
100,True,True,NaN,NaN,174592,0,0,-2,2,0,3,0.0,-0.5,0,Marcus,0.0,206,False,,None,48,174592.jpg,1.0,False,Edwards,0.1,False,None,a,3,90,1,3260,90,8530,289,0.0,0.2,Edwards,241.0,2025-07-01,1998-12-03,False,p174592,5,0,0,0,0,0,0,0,0,0,0,0,3,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,663,279,655,279,636,271,664,280,4.0,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,367,230,642,267,366,171,555,202,0.00,0.00,0.00
101,True,True,NaN,NaN,465527,0,0,-1,1,0,3,0.8,0.3,0,Hannibal,0.8,207,False,,None,49,465527.jpg,2.0,False,Mejbri,0.1,False,None,a,3,90,12,8299,222,12893,725,0.2,2.4,Hannibal,218.0,2024-08-28,2003-01-21,False,p465527,246,0,0,1,7,0,0,0,0,0,0,0,33,15.0,40.7,13.0,6.8,3,11,6,20,3,0.16,0.21,0.37,6.65,351,162,172,115,278,149,302,149,NaN,,3.0,,NaN,,0.06,0.00,0.08,0.14,2.43,2.56,342,213,302,148,262,121,423,142,1.10,0.37,7.32
102,True,False,0.0,0.0,487702,0,0,0,0,0,3,0.0,0.0,0,Luca,0.0,208,False,Has joined Espanyol on loan for the rest of th...,2025-08-22T14:15:37.649817Z,50,487702.jpg,0.0,False,Koleosho,0.0,False,None,u,3,90,0,68,0,2800,24,0.0,0.0,Koleosho,106.0,2023-07-25,2004-09-15,False,p487702,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,699,303,697,304,688,301,700,304,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,281,172,686,295,700,304,682,291,0.00,0.00,0.00
103,True,True,NaN,NaN,167887,0,0,-1,1,0,3,2.0,1.5,2,Josh,2.0,209,False,,None,49,167887.jpg,1.6,False,Laurent,0.0,False,None,a,3,90,11,880,46,1959,86,0.4,2.2,Laurent,241.0,2024-08-30,1995-05-06,False,p167887,448,0,0,0,12,0,0,0,1,0,0,0,53,52.6,21.3,32.0,10.8,23,15,2,40,5,0.16,0.14,0.30,9.42,224,97,247,147,181,107,241,122,NaN,,NaN,,NaN,,0.03,0.00,0.03,0.06,1.89,2.41,308,192,178,81,306,144,624,255,1.00,0.00,8.04
104,True,True,NaN,NaN,469272,0,0,-1,1,0,3,2.0,1.5,1,Loum,2.0,210,False,,None,49,469272.jpg,1.9,False,Tchaouna,0.0,False,None,a,3,90,13,2060,100,2200,138,0.4,2.7,Tchaouna,73.0,2025-07-02,2003-09-08,False,p469272,309,0,1,1,5,0,0,0,1,0,0,0,40,18.6,29.8,33.0,8.2,4,9,5,18,4,0.32,0.16,0.48,5.63,336,157,208,132,177,105,279,139,NaN,,NaN,,NaN,,0.09,0.00,0.05,0.14,1.64,1.46,345,215,181,83,275,129,606,242,1.17,0.29,5.24
105,True,False,0.0,0.0,447715,0,0,-1,1,0,3,0.0,0.0,0,Aaron,0.0,211,False,has joined Leicester City on loan for the rest...,2025-09-02T12:51:25.540742Z,44,447715.jpg,0.0,False,Ramsey,2.8,False,None,u,3,90,0,62789,0,768459,17037,0.0,0.0,A.Ramsey,241.0,2023-08-22,2003-01-21,False,p447715,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,553,200,541,202,516,192,555,202,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,540,301,530,187,559,205,109,38,0.00,0.00,0.00
106,True,False,0.0,0.0,576323,0,0,0,0,0,3,0.0,0.0,0,Oluwaseun,0.0,212,False,Has joined Cercle Brugge on loan for the rest ...,2025-08-15T12:03:26.649417Z,45,576323.jpg,0.0,False,Adewumi,0.0,False,None,u,3,90,0,0,0,2392,31,0.0,0.0,Adewumi,14.0,2024-08-29,2005-02-23,False,p576323,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,640,263,634,265,613,256,642,265,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,471,280,618,251,645,268,697,301,0.00,0.00,0.00
107,True,True,NaN,NaN,551206,0,0,0,0,0,3,0.0,-0.5,0,Jaydon,0.0,213,False,,None,45,551206.jpg,0.0,False,Banel,0.0,False,None,a,3,90,0,3226,240,3456,223,0.0,0.0,Banel,152.0,2025-02-03,2004-10-19,False,p551206,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,629,256,623,258,602,249,631,258,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,458,273,607,244,634,261,591,230,0.00,0.00,0.00
108,True,True,NaN,NaN,437748,0,0,-1,1,0,3,0.0,-0.5,0,Mike,0.0,214,False,,None,44,437748.jpg,0.0,False,Trésor Ndayishimiye,0.1,False,None,a,3,90,0,5649,382,6356,390,0.0,0.0,Trésor,21.0,2024-07-01,1999-05-28,False,p437748,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,551,199,539,201,513,191,553,201,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,537,300,528,186,557,204,506,175,0.00,0.00,0.00
109,True,True,NaN,NaN,431639,0,0,-2,2,0,4,0.5,0.0,1,Zian,0.5,215,False,,None,53,431639.jpg,1.0,False,Flemming,0.1,False,None,a,3,90,4,6482,304,15262,472,0.1,0.8,Flemming,152.0,2025-06-01,1998-08-01,False,p431639,32,0,0,0,0,0,0,0,0,0,0,0,11,2.2,10.1,9.0,2.0,0,1,0,1,0,0.12,0.00,0.12,0.64,406,43,314,34,295,41,381,40,NaN,,2.0,,NaN,,0.34,0.00,0.00,0.34,1.80,0.00,211,44,338,35,387,39,464,64,0.00,0.00,2.81
110,True,True,0.0,0.0,492831,0,0,-1,1,0,4,0.0,0.0,0,Zeki,0.0,216,False,Knee injury - Unknown return date,2025-08-10T22:00:04.567659Z,49,492831.jpg,0.0,False,Amdouni,0.0,False,None,i,3,90,0,673,26,4425,89,0.0,0.0,Amdouni,207.0,2023-07-19,2000-12-04,False,p492831,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,687,71,682,70,666,69,688,71,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,352,58,670,67,687,71,637,79,0.00,0.00,0.00
111,True,True,NaN,NaN,435973,0,0,0,0,0,4,2.8,2.3,1,Lyle,2.8,217,False,,None,50,435973.jpg,3.0,False,Foster,2.4,False,None,a,3,90,21,351079,23711,146355,13397,0.6,4.2,Foster,198.0,2023-01-25,2000-09-03,False,p435973,565,1,1,2,12,0,0,0,2,0,0,2,82,82.2,66.5,67.0,21.2,11,15,5,31,7,0.93,0.13,1.06,11.24,151,12,103,8,84,22,123,18,NaN,,NaN,,NaN,,0.15,0.00,0.02,0.17,1.79,1.91,271,52,132,14,152,14,121,19,1.12,0.32,4.94
112,True,True,NaN,NaN,44699,0,0,-1,1,0,4,0.0,-0.5,0,Ashley,0.0,218,False,,None,44,44699.jpg,0.0,False,Barnes,1.5,False,None,a,3,90,0,71887,2711,176723,6462,0.0,0.0,Barnes,241.0,2025-01-02,1989-10-30,False,p44699,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,537,49,523,47,494,47,539,49,NaN,,NaN,,1.0,,0.00,0.00,0.00,0.00,0.00,0.00,498,68,509,44,541,49,152,24,0.00,0.00,0.00
113,True,False,0.0,0.0,220598,0,0,-1,1,0,4,0.0,0.0,0,Michael,0.0,219,False,has joined VfL Bochum on loan for the rest of...,2025-09-02T12:51:25.555230Z,44,220598.jpg,0.0,False,Obafemi,0.2,False,None,u,3,90,0,4151,0,32779,804,0.0,0.0,Obafemi,104.0,2023-07-01,2000-07-06,False,p220598,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,545,50,533,48,505,48,547,50,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,0.00,0.00,523,69,520,45,549,50,375,56,0.00,0.00,0.00
114,True,True,100.0,100.0,67089,0,0,0,0,0,1,2.5,2.0,2,Martin,2.5,470,False,,2025-08-11T10:30:07.723845Z,40,67089.jpg,2.9,False,Dúbravka,34.1,False,None,a,3,90,20,814678,24448,485021,26585,0.6,5.0,Dúbravka,194.0,2025-08-07,1989-01-15,False,p67089,630,0,0,1,15,0,0,0,0,0,29,0,93,218.0,0.0,0.0,21.9,11,55,0,0,7,0.00,0.00,0.00,13.67,7,1,437,19,405,8,118,2,NaN,,NaN,,NaN,,0.00,4.14,0.00,0.00,1.95,2.14,612,42,139,12,161,16,5,1,1.00,0.14,0.00
115,True,True,100.0,100.0,503714,0,0,0,0,0,3,1.8,1.3,7,Lesley,1.8,676,False,,2025-09-14T22:00:08.706775Z,50,503714.jpg,2.2,False,Ugochukwu,0.0,False,None,a,3,90,13,1392,197,3404,93,0.4,2.6,Ugochukwu,73.0,2025-08-06,2004-03-26,False,p503714,285,1,0,1,6,0,0,0,0,1,0,1,50,62.4,20.7,29.0,11.0,7,8,12,27,3,0.30,0.02,0.32,6.51,192,78,250,148,192,112,239,120,NaN,,NaN,,NaN,,0.09,0.00,0.01,0.10,2.06,1.89,287,177,204,93,236,111,602,239,0.95,0.32,8.53
116,True,True,100.0,100.0,440323,0,0,-2,2,0,4,0.8,0.3,1,Armando,0.8,680,False,,2025-08-22T12:30:07.403187Z,53,440323.jpg,1.0,False,Broja,0.1,False,None,a,3,90,3,7724,431,20999,638,0.2,0.6,Broja,2.0,2025-08-08,2001-09-10,False,p440323,42,0,0,0,4,0,0,0,0,0,0,0,7,6.2,0.9,2.0,1.0,1,0,2,3,0,0.00,0.00,0.00,2.11,382,36,373,40,356,44,397,41,NaN,,NaN,,NaN,,0.00,0.00,0.00,0.00,4.52,8.57,213,45,309,31,389,40,424,60,0.00,0.00,6.43
117,True,True,NaN,NaN,216055,0,0,0,0,0,3,3.0,2.5,4,Florentino Ibrain,3.0,722,False,,None,50,216055.jpg,3.0,False,Morris Luís,0.0,False,None,a,3,90,12,978,98,488,50,0.6,2.4,Florentino,173.0,2025-09-01,1999-08-19,False,p216055,297,0,0,0,9,0,0,0,1,0,0,0,55,75.8,38.0,0.0,11.4,15,16,18,49,3,0.00,0.04,0.04,5.74,162,62,181,120,678,294,236,118,NaN,,NaN,,NaN,,0.00,0.00,0.01,0.01,1.74,2.73,262,160,122,54,151,62,691,297,0.91,0.00,14.85

In [8]:
#get list of IDs to scrape by GW stats per player
player_id_list = list(player_season_df[['id']].drop_duplicates().id)
assert len(player_id_list)== len(player_season_df)

# Players By Gameweek Stats

In [9]:
player_weekly_df = pd.DataFrame()

for pid in player_id_list:
    #print(pid)
    response = requests.get(f'https://fantasy.premierleague.com/api/element-summary/{pid}/')
    
    if response.status_code != 200:
        raise Exception("Response was code " + str(response.status_code))
        print(pid)
        
    p_data = pd.DataFrame(response.json()['history'])
    p_data['id'] = pid
    player_weekly_df = player_weekly_df.append(p_data)

In [10]:
none_check_df = (
    player_weekly_df[['element', 'id']]
    .drop_duplicates()
    .merge(player_season_df, on='id', how='outer')
)

In [11]:
print(len(player_weekly_df[['element']].drop_duplicates()))
print(len(player_season_df))

743
743

In [12]:
len(none_check_df[none_check_df['element'].isna()].query('minutes > 0'))

0

In [13]:
#for players not in weekly df, check if their total minutes are 0. 
#check to see if anyone has player > 0 mins in season df and is NOT in weekly df
assert len(none_check_df[none_check_df['element'].isna()].query('minutes > 0'))==0

In [14]:
#merge on player name and team name to player_weekly_df
player_names = player_season_df[['id', 'team', 'element_type', 'first_name', 'second_name', 'web_name']].drop_duplicates()
team_names = team_df[['id', 'name', 'short_name']].drop_duplicates().rename(columns={'id':'team'})
opponent_names = team_df[['id', 'name', 'short_name']].drop_duplicates().rename(columns={'id':'opponent_id', 'name':'opponent', 'short_name':'opponent_short_name'})


player_weekly_with_deets = (
    player_weekly_df
    .merge(player_names, left_on='id', right_on='id', how='left')
    .merge(team_names, left_on='team', right_on='team', how='left')
    .merge(opponent_names, left_on='opponent_team', right_on='opponent_id', how='left')
    .rename(columns={
        'team' : 'team_id',
        'name' : 'team'
    })
)

for var in [
    'influence', 'creativity', 'threat', 'ict_index', 'starts', 
    'expected_goals', 'expected_assists', 'expected_goal_involvements',
    'expected_goals_conceded'
]:
    player_weekly_with_deets[var] = player_weekly_with_deets[var].astype(float)

player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 1), 'position'] = 'GK'
player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 2), 'position'] = 'DEF'
player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 3), 'position'] = 'MID'
player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 4), 'position'] = 'FWD'

In [15]:
player_weekly_with_deets.head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out,id,team_id,element_type,first_name,second_name,web_name,team,short_name,opponent_id,opponent,opponent_short_name,position
0,1,9,14,10,False,2025-08-17T15:30:00Z,0,1,1,False,90,0,0,1,0,0,0,0,1,0,7,3,38,49.2,0.0,0.0,4.9,1,13,0,0,1.0,0.0,0.00,0.00,1.52,55,0,1531911,0,0,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,14,Man Utd,MUN,GK
1,1,11,11,6,True,2025-08-23T16:30:00Z,5,0,2,False,90,0,0,1,0,0,0,0,0,0,1,0,28,13.4,0.0,0.0,1.3,0,3,0,0,1.0,0.0,0.00,0.00,0.17,55,218659,2284634,277339,58680,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,11,Leeds,LEE,GK
2,1,25,12,2,False,2025-08-31T15:30:00Z,1,0,3,False,90,0,0,0,1,0,0,0,0,0,2,0,12,20.0,10.0,0.0,3.0,0,12,0,0,1.0,0.0,0.02,0.02,0.52,55,-12311,2406964,146739,159050,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,12,Liverpool,LIV,GK
3,1,31,16,6,True,2025-09-13T11:30:00Z,3,0,4,False,90,0,0,1,0,0,0,0,0,0,1,0,24,12.8,0.0,0.0,1.3,0,9,0,0,1.0,0.0,0.00,0.00,0.20,55,171289,2765759,289041,117752,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,16,Nott'm Forest,NFO,GK
4,1,41,13,2,True,2025-09-21T15:30:00Z,1,1,5,False,90,0,0,0,1,0,0,0,0,0,2,0,13,21.4,0.0,0.0,2.1,1,6,0,0,1.0,0.0,0.01,0.01,0.89,55,-9786,2762632,98100,107886,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,13,Man City,MCI,GK

# Fixtures

In [16]:
response = requests.get("https://fantasy.premierleague.com/api/fixtures/")
fixtures_df = pd.DataFrame(response.json())
fixtures_df.head()

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2561895,1,True,True,1,2025-08-15T19:00:00Z,90,False,True,4,2.0,12,4.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,5,124791
1,2561896,1,True,True,2,2025-08-16T11:30:00Z,90,False,True,15,0.0,2,0.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,4,124792
2,2561897,1,True,True,3,2025-08-16T14:00:00Z,90,False,True,10,1.0,6,1.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,3,124793
3,2561900,1,True,True,6,2025-08-16T14:00:00Z,90,False,True,3,0.0,18,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,3,124796
4,2561899,1,True,True,5,2025-08-16T14:00:00Z,90,False,True,19,0.0,17,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,2,124795

# Export

In [17]:
#export to CSV
fpl_dir = '/Users/yuta/Desktop/fpl_web_scrape/2025-2026'

team_df.to_csv(f"{fpl_dir}/teams.csv", index=False)
fixtures_df.to_csv(f"{fpl_dir}/fixtures.csv", index=False)
player_season_df.to_csv(f"{fpl_dir}/player_season_stats.csv", index=False)
#player_weekly_df.to_csv(f"{fpl_dir}/data/player_weekly_stats.csv", index=False)
player_weekly_with_deets.to_csv(f"{fpl_dir}/player_weekly_stats.csv", index=False)

In [18]:
player_weekly_with_deets.head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out,id,team_id,element_type,first_name,second_name,web_name,team,short_name,opponent_id,opponent,opponent_short_name,position
0,1,9,14,10,False,2025-08-17T15:30:00Z,0,1,1,False,90,0,0,1,0,0,0,0,1,0,7,3,38,49.2,0.0,0.0,4.9,1,13,0,0,1.0,0.0,0.00,0.00,1.52,55,0,1531911,0,0,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,14,Man Utd,MUN,GK
1,1,11,11,6,True,2025-08-23T16:30:00Z,5,0,2,False,90,0,0,1,0,0,0,0,0,0,1,0,28,13.4,0.0,0.0,1.3,0,3,0,0,1.0,0.0,0.00,0.00,0.17,55,218659,2284634,277339,58680,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,11,Leeds,LEE,GK
2,1,25,12,2,False,2025-08-31T15:30:00Z,1,0,3,False,90,0,0,0,1,0,0,0,0,0,2,0,12,20.0,10.0,0.0,3.0,0,12,0,0,1.0,0.0,0.02,0.02,0.52,55,-12311,2406964,146739,159050,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,12,Liverpool,LIV,GK
3,1,31,16,6,True,2025-09-13T11:30:00Z,3,0,4,False,90,0,0,1,0,0,0,0,0,0,1,0,24,12.8,0.0,0.0,1.3,0,9,0,0,1.0,0.0,0.00,0.00,0.20,55,171289,2765759,289041,117752,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,16,Nott'm Forest,NFO,GK
4,1,41,13,2,True,2025-09-21T15:30:00Z,1,1,5,False,90,0,0,0,1,0,0,0,0,0,2,0,13,21.4,0.0,0.0,2.1,1,6,0,0,1.0,0.0,0.01,0.01,0.89,55,-9786,2762632,98100,107886,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,13,Man City,MCI,GK