In [2]:
import glob
from PIL import Image
import os
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import requests
import json

In [3]:
#display all columns (not just first and last 5)
pd.options.display.max_columns = None

In [4]:
data = requests.get('https://fantasy.premierleague.com/api/bootstrap-static/')
data = json.loads(data.content)

for key in data:
    print (key)

chips
events
game_settings
game_config
phases
teams
total_players
element_stats
element_types
elements

# Teams

In [5]:
len(data['teams'])

20

In [6]:
team_df = pd.DataFrame(data['teams'])
team_df.head()

,code,draw,form,id,loss,name,played,points,position,short_name,strength,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,2,ARS,4,None,False,0,1320,1325,1350,1350,1290,1300,1
1,7,0,None,2,0,Aston Villa,0,0,19,AVL,3,None,False,0,1125,1250,1110,1200,1140,1300,2
2,90,0,None,3,0,Burnley,0,0,17,BUR,2,None,False,0,1050,1050,1050,1050,1050,1050,43
3,91,0,None,4,0,Bournemouth,0,0,4,BOU,3,None,False,0,1150,1180,1100,1160,1200,1200,127
4,94,0,None,5,0,Brentford,0,0,12,BRE,3,None,False,0,1120,1185,1080,1080,1160,1290,130

# Players Season Cumulative Stats

In [7]:
player_season_df = pd.DataFrame(data['elements'])
player_season_df.sort_values('minutes', ascending=False).head()

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,removed,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,region,team_join_date,birth_date,has_temporary_code,opta_code,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,expected_goals_per_90,saves_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,goals_conceded_per_90,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,defensive_contribution_per_90
0,True,True,NaN,NaN,154561,0,0,0,0,1,1,4.7,5.2,6,David,4.7,1,False,,None,55,154561.jpg,6.0,False,Raya Martín,23.4,False,None,a,1,3,24,776539,63420,399302,63820,0.9,4.4,Raya,200.0,2024-07-04,1995-09-15,False,p154561,360,0,0,3,1,0,0,0,1,0,11,3,102,95.4,10.0,0.0,10.5,1,37,0,0,4,0.00,0.02,0.02,2.41,31,5,260,5,710,85,138,3,NaN,,NaN,,NaN,,0.00,2.75,0.00,0.00,0.60,0.25,138,3,61,8,27,5,14,2,1.0,0.75,0.00
555,True,True,NaN,NaN,227444,0,0,0,0,0,2,1.8,0.8,1,Nikola,1.3,505,False,,None,55,227444.jpg,1.5,False,Milenković,7.5,False,None,a,16,17,6,147442,19845,359799,48579,0.2,1.1,Milenković,190.0,2024-07-18,1997-10-12,False,p227444,360,0,0,0,8,0,0,0,0,0,0,0,18,54.6,5.0,10.0,7.0,22,10,2,24,4,0.05,0.05,0.10,6.86,115,50,295,99,222,62,211,67,NaN,,NaN,,NaN,,0.01,0.00,0.01,0.02,1.72,2.00,151,20,241,83,281,96,57,21,1.0,0.00,6.00
534,True,True,NaN,NaN,208706,0,0,0,0,0,3,4.2,4.2,2,Bruno,3.7,488,False,,None,65,208706.jpg,3.5,False,Guimarães Rodriguez Moura,2.5,False,None,a,15,4,14,147375,10450,89751,19699,0.6,2.2,Bruno G.,30.0,2022-01-30,1997-11-16,False,p208706,360,1,0,3,3,0,0,0,2,0,0,0,56,59.4,72.8,25.0,15.7,2,29,8,39,4,0.25,0.22,0.47,2.09,109,36,42,37,135,79,70,45,NaN,,NaN,,NaN,,0.06,0.00,0.06,0.12,0.52,0.75,55,37,100,37,134,53,113,39,1.0,0.75,9.75
523,True,True,NaN,NaN,441191,0,0,1,-1,0,2,5.8,5.8,6,Tino,5.3,477,False,,None,51,441191.jpg,6.2,False,Livramento,9.5,False,None,a,15,4,25,779999,58721,152748,23934,1.0,4.9,Livramento,241.0,2023-08-08,2002-11-12,False,p441191,360,0,1,3,3,0,0,0,0,0,0,3,88,55.6,50.4,14.0,12.0,6,19,4,10,4,0.00,0.30,0.30,2.09,114,49,73,17,200,50,119,37,NaN,,NaN,,NaN,,0.00,0.00,0.08,0.08,0.52,0.75,236,34,41,18,22,12,43,15,1.0,0.75,2.50
522,True,True,NaN,NaN,78916,0,0,0,0,0,2,5.2,5.2,6,Dan,4.7,476,False,,None,50,78916.jpg,5.8,False,Burn,5.6,False,None,a,15,4,23,295451,19859,112306,15411,0.9,4.6,Burn,241.0,2022-01-31,1992-05-09,False,p78916,360,0,0,3,3,0,0,0,1,0,0,1,76,59.2,17.3,23.0,10.0,26,14,4,30,4,0.05,0.09,0.14,2.09,110,48,195,55,142,29,149,52,NaN,,NaN,,NaN,,0.01,0.00,0.02,0.03,0.52,0.75,240,36,59,28,37,16,65,26,1.0,0.75,7.50

In [8]:
player_season_df.query('team==3')

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,removed,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,region,team_join_date,birth_date,has_temporary_code,opta_code,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,expected_goals_per_90,saves_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,goals_conceded_per_90,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,defensive_contribution_per_90
77,True,True,NaN,NaN,518030,-1,1,-1,1,0,1,-0.5,-1.5,0,Max,0.0,183,False,,None,44,518030.jpg,0.0,False,Weiß,0.1,False,None,a,3,90,0,1974,355,6830,656,0.0,0.0,Weiss,80.0,2025-06-25,2004-06-15,False,p518030,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,539,78,526,63,490,56,543,78,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,578,38,535,77,546,78,426,62,0.00,0.00,0.00
78,True,False,0.0,0.0,489571,0,0,0,0,0,1,0.0,0.0,0,Etienne,0.0,184,False,has joined FC Fredericia permanently.,2025-09-02T12:51:25.510909Z,40,489571.jpg,0.0,False,Green,0.3,False,None,u,3,90,0,4943,0,14834,2435,0.0,0.0,Green,241.0,2024-08-07,2000-07-19,False,p489571,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,458,59,445,44,401,37,462,59,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,677,75,452,58,466,59,292,43,0.00,0.00,0.00
79,True,True,NaN,NaN,51943,0,0,0,0,0,1,-0.5,-1.5,0,Václav,0.0,185,False,,None,40,51943.jpg,0.0,False,Hladký,0.2,False,None,a,3,90,0,3095,651,5651,607,0.0,0.0,Hladký,57.0,2024-07-19,1990-11-14,False,p51943,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,401,26,385,9,339,2,405,26,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,606,40,397,25,411,26,375,56,0.00,0.00,0.00
80,True,True,25.0,0.0,192290,0,0,-1,1,0,2,-0.1,0.0,0,Connor,0.0,186,False,Knock - 25% chance of playing,2025-08-22T12:30:06.986449Z,44,192290.jpg,0.0,False,Roberts,0.0,False,None,d,3,90,0,548,16,6022,376,0.0,0.0,Roberts,244.0,2021-08-31,1995-09-23,False,p192290,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,515,214,502,213,461,195,519,214,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,535,128,509,208,522,211,585,207,0.00,0.00,0.00
81,True,True,NaN,NaN,58621,0,0,0,0,0,2,2.2,1.2,2,Kyle,2.7,187,False,,None,45,58621.jpg,2.2,False,Walker,1.7,False,None,a,3,90,9,46529,6461,78705,8306,0.6,2.0,Walker,241.0,2025-07-05,1990-05-28,False,p58621,360,0,0,1,7,0,0,0,1,0,0,0,28,47.6,8.1,1.0,5.7,18,14,5,23,4,0.01,0.14,0.15,9.17,137,62,269,89,321,110,241,82,NaN,,NaN,,NaN,,0.00,0.0,0.04,0.04,2.29,1.75,389,70,131,57,207,77,136,53,1.00,0.25,5.75
82,True,True,NaN,NaN,247245,0,0,0,0,0,2,-0.5,-1.5,0,Hannes,0.0,188,False,,None,40,247245.jpg,0.0,False,Delcroix,0.2,False,None,a,3,90,0,3761,458,12144,1139,0.0,0.0,Delcroix,21.0,2023-08-22,1999-02-28,False,p247245,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,433,162,420,161,375,139,437,162,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,646,176,427,156,441,160,329,116,0.00,0.00,0.00
83,True,False,0.0,0.0,461567,0,0,0,0,0,2,0.0,0.0,0,Owen,0.0,189,False,Has joined Stockport County on loan for the re...,2025-08-11T01:08:30.737822Z,40,461567.jpg,0.0,False,Dodgson,0.0,False,None,u,3,90,0,0,0,1724,78,0.0,0.0,Dodgson,241.0,2021-08-20,2003-03-19,False,p461567,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,445,170,432,169,387,147,449,170,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,660,186,439,164,453,168,657,221,0.00,0.00,0.00
84,True,True,NaN,NaN,478969,0,0,0,0,0,2,4.8,3.8,4,Hjalmar,5.3,190,False,,None,40,478969.jpg,4.2,False,Ekdal,1.4,False,None,a,3,90,17,153467,19106,40831,4972,1.3,4.2,Ekdal,206.0,2023-01-21,1998-10-21,False,p478969,352,0,0,1,6,0,0,0,0,0,0,1,48,93.8,15.4,18.0,12.7,38,10,5,43,4,0.01,0.01,0.02,8.11,40,13,209,65,173,38,107,31,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,2.07,1.53,673,193,37,15,82,38,163,61,1.02,0.26,10.99
85,True,True,NaN,NaN,477717,0,0,0,0,0,2,3.2,2.2,4,Maxime,3.7,191,False,,None,40,477717.jpg,3.0,False,Estève,16.5,False,None,a,3,90,12,286136,24078,483734,42218,0.9,3.0,Estève,73.0,2024-06-14,2002-05-26,False,p477717,352,0,0,1,7,0,0,0,0,0,0,0,37,93.6,1.9,19.0,11.5,36,4,2,38,4,0.05,0.01,0.06,9.06,41,14,327,116,167,36,125,40,NaN,,NaN,,NaN,,0.01,0.0,0.00,0.01,2.32,1.79,672,192,92,40,152,65,24,7,1.02,0.26,9.72
86,True,True,NaN,NaN,494960,0,0,0,0,0,2,3.2,2.2,4,Quilindschy,3.7,192,False,,None,40,494960.jpg,3.0,False,Hartman,0.5,False,None,a,3,90,12,22184,2857,22071,1843,0.9,3.0,Hartman,152.0,2025-06-26,2001-11-14,False,p494960,360,0,0,1,7,0,0,0,0,0,0,0,40,78.2,31.0,11.0,12.0,30,10,10,40,4,0.09,0.09,0.18,9.17,69,29,115,27,217,59,118,36,2.0,,NaN,,NaN,,0.02,0.0,0.02,0.04,2.29,1.75,682,197,93,41,153,66,240,89,1.00,0.25,10.00
87,True,True,100.0,100.0,461188,0,0,0,0,0,2,-0.5,-1.5,0,Bashir,0.0,193,False,,2025-08-10T22:00:04.557380Z,40,461188.jpg,0.0,False,Humphreys,0.1,False,None,a,3,90,0,992,190,2401,247,0.0,0.0,Humphreys,241.0,2025-07-01,2003-03-15,False,p461188,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,442,168,429,167,384,145,446,168,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,657,184,436,162,450,166,568,205,0.00,0.00,0.00
88,True,True,25.0,0.0,241231,0,0,0,0,0,2,-0.1,0.0,0,Jordan,0.0,194,False,Hamstring injury - 25% chance of playing,2025-08-22T12:30:07.019474Z,40,241231.jpg,0.0,False,Beyer,0.1,False,None,d,3,90,0,728,16,9601,664,0.0,0.0,Jordan,80.0,2023-07-01,2000-05-19,False,p241231,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,432,161,419,160,374,138,436,161,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,644,174,426,155,440,159,480,180,0.00,0.00,0.00
89,True,True,NaN,NaN,549329,-1,1,-1,1,0,2,-0.5,-1.5,0,Lucas,0.0,195,False,,None,39,549329.jpg,0.0,False,Pires Silva,0.2,False,None,a,3,90,0,4059,3050,6369,951,0.0,0.0,Lucas Pires,30.0,2024-07-16,2001-03-24,False,p549329,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,394,144,377,141,331,118,398,144,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,734,239,390,140,404,144,389,142,0.00,0.00,0.00
90,True,False,0.0,0.0,450072,0,0,0,0,0,2,0.0,0.0,0,Shurandy,0.0,196,False,Has joined Sparta Rotterdam on loan for the re...,2025-08-19T13:36:42.853472Z,40,450072.jpg,0.0,False,Sambo,0.1,False,None,u,3,90,0,202,0,6804,365,0.0,0.0,Sambo,152.0,2024-06-28,2001-08-19,False,p450072,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,441,167,428,166,383,144,445,167,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,656,183,435,161,449,165,537,197,0.00,0.00,0.00
91,True,True,NaN,NaN,519895,0,0,0,0,0,2,0.2,-0.8,0,Oliver,0.7,197,False,,None,40,519895.jpg,1.0,False,Sonne,0.1,False,None,a,3,90,3,3225,237,5321,616,0.2,0.8,Sonne,169.0,2025-01-01,2000-11-10,False,p519895,102,0,0,0,4,0,0,0,0,0,0,0,-2,7.6,16.4,6.0,3.0,1,3,1,2,1,0.03,0.08,0.11,3.31,328,124,201,59,256,80,317,106,NaN,,NaN,,NaN,,0.03,0.0,0.07,0.10,2.92,3.53,697,209,298,96,308,107,419,156,0.88,0.00,1.76
92,True,True,100.0,100.0,180804,0,0,-1,1,0,2,-0.5,-1.5,0,Axel,0.0,198,False,,2025-08-22T12:30:07.036752Z,39,180804.jpg,0.0,False,Tuanzebe,2.0,False,None,a,3,90,0,58847,17070,97585,9728,0.0,0.0,Tuanzebe,50.0,2025-07-01,1997-11-14,False,p180804,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,388,138,371,135,325,112,392,138,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,728,233,384,134,398,138,128,51,0.00,0.00,0.00
93,True,True,NaN,NaN,208912,0,0,0,0,0,2,0.5,-0.5,1,Joe,1.0,199,False,,None,40,208912.jpg,1.0,False,Worrall,0.1,False,None,a,3,90,3,1500,243,4598,454,0.2,0.8,Worrall,241.0,2024-08-23,1997-01-10,False,p208912,18,0,0,0,2,0,0,0,0,0,0,0,6,11.0,0.0,0.0,1.1,5,1,1,6,0,0.00,0.00,0.00,2.17,305,115,408,155,363,133,356,125,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,10.85,10.00,632,168,253,85,304,103,444,170,0.00,0.00,30.00
94,True,True,NaN,NaN,444180,0,0,0,0,1,3,6.8,5.8,3,Jaidon,7.3,200,False,,None,55,444180.jpg,6.0,False,Anthony,1.2,False,None,a,3,90,24,129935,37122,36440,8730,1.3,4.4,Anthony,241.0,2025-07-01,1999-12-01,False,p444180,352,2,1,2,6,0,0,0,1,0,0,2,75,115.6,42.1,96.0,25.4,8,19,5,32,4,1.70,0.39,2.09,8.23,16,8,88,62,16,7,17,13,3.0,,1.0,,NaN,,0.43,0.0,0.10,0.53,2.10,1.53,158,97,12,4,30,8,170,56,1.02,0.51,8.18
95,True,True,NaN,NaN,183751,0,0,-1,1,0,3,-0.5,-1.5,0,Manuel,0.0,201,False,,None,54,183751.jpg,0.0,False,Benson Hedilazio,0.0,False,None,a,3,90,0,902,173,1666,235,0.0,0.0,Benson,6.0,2022-08-04,1997-03-28,False,p183751,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,703,305,703,306,689,302,704,306,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,181,112,700,303,705,306,637,267,0.00,0.00,0.00
96,True,True,75.0,NaN,179458,0,0,-1,1,0,3,1.7,1.2,0,Jacob,2.7,202,False,Knock - 75% chance of playing,2025-09-14T22:00:08.065375Z,54,179458.jpg,3.0,False,Bruun Larsen,0.0,False,None,d,3,90,9,1530,99,2699,477,0.5,1.7,Bruun Larsen,58.0,2025-07-11,1998-09-19,False,p179458,176,0,1,1,3,0,0,0,0,0,0,0,30,32.8,29.1,20.0,8.0,6,6,1,13,2,0.05,0.34,0.39,4.09,203,86,125,86,162,98,186,92,NaN,,NaN,,2.0,,0.03,0.0,0.17,0.20,2.09,1.53,180,111,148,58,164,65,605,244,1.02,0.51,6.65
97,True,True,NaN,NaN,578614,0,0,-1,1,0,3,-0.5,-1.5,0,Enock,0.0,203,False,,None,49,578614.jpg,0.0,False,Agyei,0.0,False,None,a,3,90,0,776,116,2953,253,0.0,0.0,Boateng,21.0,2023-01-30,2005-01-13,False,p578614,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,673,284,668,286,644,278,675,286,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,373,235,670,283,675,286,588,229,0.00,0.00,0.00
98,True,False,0.0,0.0,250735,0,0,-1,1,0,3,0.0,0.0,0,Darko,0.0,204,False,has joined Kocaelispor permanently.,2025-09-02T12:51:25.524903Z,49,250735.jpg,0.0,False,Churlinov,0.0,False,None,u,3,90,0,160,0,1507,157,0.0,0.0,Churlinov,NaN,2022-08-19,2000-07-11,False,p250735,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,661,275,654,276,630,268,663,277,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,346,215,658,274,664,278,660,281,0.00,0.00,0.00
99,True,True,NaN,NaN,172567,0,0,0,0,1,3,5.8,4.8,3,Josh,6.3,205,False,,None,50,172567.jpg,5.8,False,Cullen,2.0,False,None,a,3,90,23,255265,24346,81560,14097,1.3,4.6,Cullen,104.0,2022-07-12,1996-04-07,False,p172567,332,1,1,2,6,1,0,0,0,0,0,3,89,121.6,81.2,21.0,22.4,20,13,7,40,4,0.08,0.52,0.60,7.93,12,5,29,26,149,88,24,17,1.0,,NaN,,NaN,,0.02,0.0,0.14,0.16,2.15,1.63,251,154,23,9,38,12,127,43,1.08,0.54,10.84
100,True,True,NaN,NaN,174592,-1,1,-2,2,0,3,-0.5,-1.5,0,Marcus,0.0,206,False,,None,48,174592.jpg,1.0,False,Edwards,0.1,False,None,a,3,90,1,1427,407,5970,535,0.0,0.2,Edwards,241.0,2025-07-01,1998-12-03,False,p174592,5,0,0,0,0,0,0,0,0,0,0,0,3,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,640,263,634,265,606,254,643,266,4.0,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,379,240,636,262,332,154,550,203,0.00,0.00,0.00
101,True,True,NaN,NaN,465527,0,0,0,0,0,3,2.2,1.2,1,Hannibal,2.7,207,False,,None,50,465527.jpg,2.5,False,Mejbri,0.2,False,None,a,3,90,10,6281,804,7658,1095,0.5,2.0,Hannibal,218.0,2024-08-28,2003-01-21,False,p465527,235,0,0,1,5,0,0,0,0,0,0,0,24,12.0,26.6,13.0,5.1,3,10,6,19,3,0.16,0.13,0.29,5.69,297,141,140,94,203,120,259,127,NaN,,3.0,,NaN,,0.06,0.0,0.05,0.11,2.18,1.91,281,170,145,55,189,84,398,135,1.15,0.38,7.28
102,True,False,0.0,0.0,487702,0,0,0,0,0,3,0.0,0.0,0,Luca,0.0,208,False,Has joined Espanyol on loan for the rest of th...,2025-08-22T14:15:37.649817Z,50,487702.jpg,0.0,False,Koleosho,0.0,False,None,u,3,90,0,68,0,2492,115,0.0,0.0,Koleosho,106.0,2023-07-25,2004-09-15,False,p487702,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,688,296,688,297,669,290,689,297,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,289,175,684,294,689,297,667,285,0.00,0.00,0.00
103,True,True,NaN,NaN,167887,0,0,-1,1,0,3,0.5,-0.5,2,Josh,1.0,209,False,,None,49,167887.jpg,1.2,False,Laurent,0.0,False,None,a,3,90,5,534,121,1420,139,0.2,1.0,Laurent,241.0,2024-08-30,1995-05-06,False,p167887,187,0,0,0,4,0,0,0,1,0,0,0,20,30.0,12.4,23.0,6.7,12,6,2,20,2,0.12,0.13,0.25,5.15,211,91,230,136,141,83,215,108,NaN,,NaN,,NaN,,0.06,0.0,0.06,0.12,2.48,1.93,320,198,262,124,291,142,628,260,0.96,0.00,9.63
104,True,True,NaN,NaN,469272,0,0,-1,1,0,3,1.8,0.8,3,Loum,2.3,210,False,,None,49,469272.jpg,2.0,False,Tchaouna,0.0,False,None,a,3,90,8,793,513,1231,173,0.5,1.6,Tchaouna,73.0,2025-07-02,2003-09-08,False,p469272,110,0,1,1,1,0,0,0,1,0,0,0,25,11.6,17.4,20.0,5.0,1,5,2,8,1,0.21,0.05,0.26,2.80,302,143,194,124,156,93,263,130,NaN,,NaN,,NaN,,0.17,0.0,0.04,0.21,2.29,0.82,357,223,167,70,232,108,621,253,0.82,0.82,6.55
105,True,False,0.0,0.0,447715,0,0,-1,1,0,3,0.0,0.0,0,Aaron,0.0,211,False,has joined Leicester City on loan for the rest...,2025-09-02T12:51:25.540742Z,44,447715.jpg,0.0,False,Ramsey,4.7,False,None,u,3,90,0,62789,0,560083,69821,0.0,0.0,A.Ramsey,241.0,2023-08-22,2003-01-21,False,p447715,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,525,186,512,189,473,175,529,189,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,556,308,520,186,532,194,79,25,0.00,0.00,0.00
106,True,False,0.0,0.0,576323,0,0,0,0,0,3,0.0,0.0,0,Oluwaseun,0.0,212,False,Has joined Cercle Brugge on loan for the rest ...,2025-08-15T12:03:26.649417Z,45,576323.jpg,0.0,False,Adewumi,0.0,False,None,u,3,90,0,0,0,2084,95,0.0,0.0,Adewumi,14.0,2024-08-29,2005-02-23,False,p576323,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,619,247,614,250,585,238,622,250,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,491,288,617,248,626,255,680,294,0.00,0.00,0.00
107,True,True,NaN,NaN,551206,0,0,0,0,0,3,-0.5,-1.5,0,Jaydon,0.0,213,False,,None,45,551206.jpg,0.0,False,Banel,0.0,False,None,a,3,90,0,1562,428,2063,278,0.0,0.0,Banel,152.0,2025-02-03,2004-10-19,False,p551206,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,606,239,601,242,572,230,610,242,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,477,280,604,240,613,247,602,241,0.00,0.00,0.00
108,True,True,NaN,NaN,437748,0,0,0,0,0,3,-0.5,-1.5,0,Mike,0.0,214,False,,None,45,437748.jpg,0.0,False,Trésor Ndayishimiye,0.1,False,None,a,3,90,0,1666,327,3753,386,0.0,0.0,Trésor,21.0,2024-07-01,1999-05-28,False,p437748,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,577,212,569,215,539,203,581,215,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,430,250,574,213,583,220,551,204,0.00,0.00,0.00
109,True,True,NaN,NaN,431639,0,0,-1,1,0,4,-0.2,-1.2,0,Zian,0.3,215,False,,None,54,431639.jpg,1.0,False,Flemming,0.1,False,None,a,3,90,2,4859,617,11520,979,0.1,0.4,Flemming,152.0,2025-06-01,1998-08-01,False,p431639,20,0,0,0,0,0,0,0,0,0,0,0,6,2.2,10.0,2.0,1.4,0,0,0,0,0,0.00,0.00,0.00,0.34,366,34,259,24,316,39,348,34,NaN,,2.0,,NaN,,0.00,0.0,0.00,0.00,1.53,0.00,193,44,374,40,360,35,458,64,0.00,0.00,0.00
110,True,True,0.0,0.0,492831,0,0,-1,1,0,4,0.0,0.0,0,Zeki,0.0,216,False,Knee injury - Unknown return date,2025-08-10T22:00:04.567659Z,49,492831.jpg,0.0,False,Amdouni,0.0,False,None,i,3,90,0,328,42,3840,207,0.0,0.0,Amdouni,207.0,2023-07-19,2000-12-04,False,p492831,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,669,67,663,67,639,64,671,67,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,363,58,666,67,672,68,635,76,0.00,0.00,0.00
111,True,True,NaN,NaN,435973,0,0,0,0,0,4,2.8,1.8,2,Lyle,3.3,217,False,,None,50,435973.jpg,3.0,False,Foster,1.2,False,None,a,3,90,12,130513,42079,55199,9738,0.7,2.4,Foster,198.0,2023-01-25,2000-09-03,False,p435973,333,1,0,2,6,0,0,0,1,0,0,1,51,54.0,30.9,41.0,12.7,7,11,5,23,4,0.73,0.05,0.78,7.83,118,11,118,9,79,23,108,16,NaN,,NaN,,NaN,,0.20,0.0,0.01,0.21,2.12,1.62,276,52,105,9,162,13,172,29,1.08,0.54,6.22
112,True,True,NaN,NaN,44699,0,0,-1,1,0,4,-0.5,-1.5,0,Ashley,0.0,218,False,,None,44,44699.jpg,0.0,False,Barnes,1.6,False,None,a,3,90,0,43590,9796,126926,10058,0.0,0.0,Barnes,241.0,2025-01-02,1989-10-30,False,p44699,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,504,43,491,43,448,41,508,44,NaN,,NaN,,1.0,,0.00,0.0,0.00,0.00,0.00,0.00,518,67,499,44,511,45,141,21,0.00,0.00,0.00
113,True,False,0.0,0.0,220598,0,0,-1,1,0,4,0.0,0.0,0,Michael,0.0,219,False,has joined VfL Bochum on loan for the rest of...,2025-09-02T12:51:25.555230Z,44,220598.jpg,0.0,False,Obafemi,0.2,False,None,u,3,90,0,4151,0,25216,2817,0.0,0.0,Obafemi,104.0,2023-07-01,2000-07-06,False,p220598,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0,0.00,0.00,0.00,0.00,518,44,505,44,464,42,522,45,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,0.00,0.00,541,68,512,45,525,46,331,54,0.00,0.00,0.00
114,True,True,100.0,100.0,67089,0,0,0,0,0,1,3.2,2.2,3,Martin,3.7,470,False,,2025-08-11T10:30:07.723845Z,40,67089.jpg,3.2,False,Dúbravka,34.0,False,None,a,3,90,13,524433,60120,275478,29058,0.9,3.2,Dúbravka,194.0,2025-08-07,1989-01-15,False,p67089,360,0,0,1,7,0,0,0,0,0,12,0,53,93.0,0.0,0.0,9.3,8,35,0,0,4,0.00,0.00,0.00,9.17,43,8,387,11,342,4,166,8,NaN,,NaN,,NaN,,0.00,3.0,0.00,0.00,2.29,1.75,609,42,91,11,144,16,5,1,1.00,0.25,0.00
115,True,True,0.0,100.0,503714,0,0,0,0,0,3,0.0,-0.2,-1,Lesley,1.3,676,False,Suspended until 27 Sep,2025-09-14T22:00:08.706775Z,50,503714.jpg,1.2,False,Ugochukwu,0.0,False,None,s,3,90,5,907,94,2356,420,0.3,1.0,Ugochukwu,73.0,2025-08-06,2004-03-26,False,p503714,253,0,0,1,4,0,0,0,0,1,0,0,20,23.8,18.8,8.0,4.9,7,8,9,24,3,0.07,0.02,0.09,5.47,238,106,188,121,239,133,266,132,NaN,,NaN,,NaN,,0.02,0.0,0.01,0.03,1.95,1.42,297,182,233,111,293,144,598,239,1.07,0.36,8.54
116,True,True,100.0,100.0,440323,0,0,-1,1,0,4,-0.2,-1.2,1,Armando,0.3,680,False,,2025-08-22T12:30:07.403187Z,54,440323.jpg,1.0,False,Broja,0.2,False,None,a,3,90,1,5161,919,16106,1078,0.1,0.2,Broja,2.0,2025-08-08,2001-09-10,False,p440323,1,0,0,0,1,0,0,0,0,0,0,0,3,2.0,0.1,0.0,0.2,1,0,0,1,0,0.00,0.00,0.00,0.94,371,37,367,40,695,70,386,42,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,84.60,90.00,197,45,375,41,362,36,403,60,0.00,0.00,90.00
117,True,True,NaN,NaN,216055,0,0,0,0,0,3,1.1,0.1,1,Florentino Ibrain,1.0,722,False,,None,50,216055.jpg,1.0,False,Morris Luís,0.0,False,None,a,3,90,1,304,122,101,71,0.2,0.2,Florentino,173.0,2025-09-01,1999-08-19,False,p216055,27,0,0,0,1,0,0,0,0,0,0,0,5,13.0,0.2,0.0,1.3,2,2,3,7,0,0.00,0.00,0.00,1.24,294,138,362,186,657,282,352,171,NaN,,NaN,,NaN,,0.00,0.0,0.00,0.00,4.13,3.33,265,162,267,128,349,164,720,315,0.00,0.00,23.33

In [9]:
#get list of IDs to scrape by GW stats per player
player_id_list = list(player_season_df[['id']].drop_duplicates().id)
assert len(player_id_list)== len(player_season_df)

# Players By Gameweek Stats

In [10]:
player_weekly_df = pd.DataFrame()

for pid in player_id_list:
    #print(pid)
    response = requests.get(f'https://fantasy.premierleague.com/api/element-summary/{pid}/')
    
    if response.status_code != 200:
        raise Exception("Response was code " + str(response.status_code))
        print(pid)
        
    p_data = pd.DataFrame(response.json()['history'])
    p_data['id'] = pid
    player_weekly_df = player_weekly_df.append(p_data)

In [11]:
none_check_df = (
    player_weekly_df[['element', 'id']]
    .drop_duplicates()
    .merge(player_season_df, on='id', how='outer')
)

In [12]:
print(len(player_weekly_df[['element']].drop_duplicates()))
print(len(player_season_df))

740
740

In [13]:
len(none_check_df[none_check_df['element'].isna()].query('minutes > 0'))

0

In [14]:
#for players not in weekly df, check if their total minutes are 0. 
#check to see if anyone has player > 0 mins in season df and is NOT in weekly df
assert len(none_check_df[none_check_df['element'].isna()].query('minutes > 0'))==0

In [15]:
#merge on player name and team name to player_weekly_df
player_names = player_season_df[['id', 'team', 'element_type', 'first_name', 'second_name', 'web_name']].drop_duplicates()
team_names = team_df[['id', 'name', 'short_name']].drop_duplicates().rename(columns={'id':'team'})
opponent_names = team_df[['id', 'name', 'short_name']].drop_duplicates().rename(columns={'id':'opponent_id', 'name':'opponent', 'short_name':'opponent_short_name'})


player_weekly_with_deets = (
    player_weekly_df
    .merge(player_names, left_on='id', right_on='id', how='left')
    .merge(team_names, left_on='team', right_on='team', how='left')
    .merge(opponent_names, left_on='opponent_team', right_on='opponent_id', how='left')
    .rename(columns={
        'team' : 'team_id',
        'name' : 'team'
    })
)

for var in [
    'influence', 'creativity', 'threat', 'ict_index', 'starts', 
    'expected_goals', 'expected_assists', 'expected_goal_involvements',
    'expected_goals_conceded'
]:
    player_weekly_with_deets[var] = player_weekly_with_deets[var].astype(float)

player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 1), 'position'] = 'GK'
player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 2), 'position'] = 'DEF'
player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 3), 'position'] = 'MID'
player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 4), 'position'] = 'FWD'

In [16]:
player_weekly_with_deets.head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,clearances_blocks_interceptions,recoveries,tackles,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out,id,team_id,element_type,first_name,second_name,web_name,team,short_name,opponent_id,opponent,opponent_short_name,position
0,1,9,14,10,False,2025-08-17T15:30:00Z,0,1,1,False,90,0,0,1,0,0,0,0,1,0,7,3,38,49.2,0.0,0.0,4.9,1,13,0,0,1.0,0.0,0.00,0.00,1.52,55,0,1531911,0,0,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,14,Man Utd,MUN,GK
1,1,11,11,6,True,2025-08-23T16:30:00Z,5,0,2,False,90,0,0,1,0,0,0,0,0,0,1,0,28,13.4,0.0,0.0,1.3,0,3,0,0,1.0,0.0,0.00,0.00,0.17,55,218659,2284634,277339,58680,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,11,Leeds,LEE,GK
2,1,25,12,2,False,2025-08-31T15:30:00Z,1,0,3,False,90,0,0,0,1,0,0,0,0,0,2,0,12,20.0,10.0,0.0,3.0,0,12,0,0,1.0,0.0,0.02,0.02,0.52,55,-12311,2406964,146739,159050,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,12,Liverpool,LIV,GK
3,1,31,16,6,True,2025-09-13T11:30:00Z,3,0,4,False,90,0,0,1,0,0,0,0,0,0,1,0,24,12.8,0.0,0.0,1.3,0,9,0,0,1.0,0.0,0.00,0.00,0.20,55,171289,2765759,289041,117752,1,1,1,David,Raya Martín,Raya,Arsenal,ARS,16,Nott'm Forest,NFO,GK
4,2,9,14,0,False,2025-08-17T15:30:00Z,0,1,1,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.00,0.00,45,0,90618,0,0,2,1,1,Kepa,Arrizabalaga Revuelta,Arrizabalaga,Arsenal,ARS,14,Man Utd,MUN,GK

# Fixtures

In [17]:
response = requests.get("https://fantasy.premierleague.com/api/fixtures/")
fixtures_df = pd.DataFrame(response.json())
fixtures_df.head()

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2561895,1,True,True,1,2025-08-15T19:00:00Z,90,False,True,4,2.0,12,4.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,5,124791
1,2561896,1,True,True,2,2025-08-16T11:30:00Z,90,False,True,15,0.0,2,0.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,4,124792
2,2561897,1,True,True,3,2025-08-16T14:00:00Z,90,False,True,10,1.0,6,1.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,3,124793
3,2561900,1,True,True,6,2025-08-16T14:00:00Z,90,False,True,3,0.0,18,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,3,124796
4,2561899,1,True,True,5,2025-08-16T14:00:00Z,90,False,True,19,0.0,17,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,2,124795

# Export

In [18]:
#export to CSV
fpl_dir = '/Users/yuta/Desktop/fpl_web_scrape/2025-2026'

team_df.to_csv(f"{fpl_dir}/teams.csv", index=False)
fixtures_df.to_csv(f"{fpl_dir}/fixtures.csv", index=False)
player_season_df.to_csv(f"{fpl_dir}/player_season_stats.csv", index=False)
#player_weekly_df.to_csv(f"{fpl_dir}/data/player_weekly_stats.csv", index=False)
player_weekly_with_deets.to_csv(f"{fpl_dir}/player_weekly_stats.csv", index=False)