In [1]:
import glob
from PIL import Image
import os
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import requests
import json
import time

from bs4 import BeautifulSoup

In [2]:

#display all columns (not just first and last 5)
pd.options.display.max_columns = None

In [3]:
# for traffic limit:
# https://www.sports-reference.com/bot-traffic.html

In [4]:
user_agent_list = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.2420.81',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 OPR/109.0.0.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 14.4; rv:124.0) Gecko/20100101 Firefox/124.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 OPR/109.0.0.0',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    'Mozilla/5.0 (X11; Linux i686; rv:124.0) Gecko/20100101 Firefox/124.0',
]

In [5]:
headers = {
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'accept-language': 'en-US,en;q=0.9',
    'cache-control': 'max-age=0',
    #'if-modified-since': 'Thu, 22 May 2025 17:41:23 GMT',
    'priority': 'u=0, i',
#     'sec-ch-ua': '"Chromium";v="136", "Google Chrome";v="136", "Not.A/Brand";v="99"',
#     'sec-ch-ua-mobile': '?0',
#     'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'none',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
    # 'cookie': 'osano_consentmanager_uuid=ef80ee15-7ba1-4791-b7f2-865f9fe1c04c; _ga=GA1.1.1181001228.1745513799; _lc2_fpi=6fbc725567fc--01jsmbnqy8vjns34qjv841trve; _lc2_fpi_meta=%7B%22w%22%3A1745513799624%7D; _lr_env_src_ats=false; gamera_user_id=5af48dbf-cb2e-47b9-b2c4-1589b5c9046a; _cc_id=8c2dd72220b52c18ac50d5761d80a8f8; _sharedid=f1f0c558-d27f-460c-acba-6a279f2d6dd5; ccuid=7af0fbcb-c7c8-4e3b-a7dd-65f5557092f6; hubspotutk=a37a24785af3ff877ac47ba5d442e0a1; sr_lang_views-en=-0.5; sr_note_box_countdown=0; srcssfull=yes; is_live=true; _li_dcdm_c=.fbref.com; _sharedid_cst=9SzrLEgsPQ%3D%3D; hb_insticator_uid=2d837a14-b8e1-458e-a45b-ac46df6472b3; __qca=P1-23bef6ae-42c3-49f0-8f40-c41262b84fe5; pbjs_fabrickId=%7B%22fabrickId%22%3A%22E1%3AA1Rn-osazp14LkUI92JoX3tozWvc9GiPcd-uEuIQjTKgdq9K8xaD_Ja3wlh4NGMdyUJbfnc69T4wWDXPT7-NuF0LK1a9Vur-IJWK_vLJh48%22%7D; panoramaId_expiry=1748541760781; panoramaId=f0c938dd0a501317554515c9903a4945a70239d951ede15abcb9c97f2bdc1af9; panoramaIdType=panoIndiv; _lr_sampling_rate=100; __hssrc=1; sr_n=2%7CThu%2C%2022%20May%202025%2018%3A03%3A24%20GMT; __hstc=218152582.a37a24785af3ff877ac47ba5d442e0a1.1745513801734.1747936973589.1747943711872.4; _lr_retry_request=true; __cf_bm=GHv6JqUTD4Srt_9i9ZjZa2w4KJgnEv0JSj0GIhpOWPM-1747947424-1.0.1.1-_BH3H8Y35BtFtanAdUxCHAiNzZz6BQfvydtNIJwd23R1NcIxTT5mpc9sEFQn.3vJOY9Xf7Sgjn8H.QtsxtliFVWShpj.2pqfc1HtvWA.U4A; _ga_80FRT7VJ60=GS2.1.s1747943712$o5$g1$t1747947737$j0$l0$h0; _ga_T897NZ0GWZ=GS2.1.s1747943712$o5$g1$t1747947737$j0$l0$h0; cto_bidid=iFeFpV9VYUloYkF4YlZORVpYOHhoaVMwcjNBJTJCeHFwdlo1eERYaG1NNnlOSFglMkZVQnMyUGdHbGhCaHBEcDF5SSUyRlhzdjdCRnowRjQwOXlFNXJuNzZ2ciUyRjlzOUMyNFJKMzh1bXFiZUdPdzZDQmNaWm1DVVVHR1NYRng4aHVHbDNGMUliV3hIM29URU1ENnglMkJCVnJKSUpFJTJGZFRPMUElM0QlM0Q; __hssc=218152582.38.1747943711872; cto_bundle=jdqoEF9JeVB4dUVFNGIxdXRzJTJGd3JwdTElMkZkQTRNMHhUV05WUGdneEpYT3Q1Q0ZSV0ttbyUyQkRLQnRxb3pDU3V4dmlINyUyRnoxYTNRMiUyQk5qc2FIRFJwMU9ZdzF4NCUyQkxGbXdsbnlhNXhzejRBQ3BuUjdOMG1oYmk0NzlwNk4yR2VjR0JnVjRjMkFjNGVuc2NxM2duZCUyRkclMkJzV3Rjd0FYemtFb0VIRVZQclpqT0dwZGVxWGhhZUViQXdFVWYwaGEzb2Z1JTJCSVNJem9zVHowbWVITGJ6Zkp3RENKVzNUc1RNT1pyTDhRYTJuOWh0R1gzb0lNbzRZM0p6a1FpMGFsSUpXd2tCY1klMkIyUG1MN0I0WGVUQm5QejFBelU1cnhCNkoyTjZ6dG9xNllaM2JlQjZ0NUNsNlZiZ24xdjkxTTJDbEhvZHJ3anRFeENV; __gads=ID=1c580f67fe1263ae:T=1745513801:RT=1747947739:S=ALNI_MaBE8QPVcTxwnzu0LRWr89WWJoXiQ; __gpi=UID=0000109e519e38cb:T=1745513801:RT=1747947739:S=ALNI_MZY0HNGr161e1YwanVGVlUWbvL4Fg; __eoi=ID=5a6200b8b106bde6:T=1745513801:RT=1747947739:S=AA-AfjbtTQ054d4DRuJSOarDextj; pbjs_fabrickId_cst=riwMLDMsbg%3D%3D',
}

In [6]:
fpl_dir = '/Users/yuta/Desktop/fpl_web_scrape/2025-2026/FB Reference'

# Step 1: Get all EPL Teams

In [7]:
#start with premier league page
#get hrefs to all teams page to scrape player name and ids
url_epl_teams = 'https://fbref.com/en/comps/9/Premier-League-Stats'
response = requests.get(url_epl_teams, headers=headers)

soup = BeautifulSoup(response.content, "html.parser")

epl_teams_table = soup.find("table", id="results2025-202691_overall")
epl_teams_href = epl_teams_table.find_all('td', attrs = {'data-stat': 'team'})

team_hrefs_list = []
for i in epl_teams_href:
    x = i.find('a', href=True)
    team_hrefs_list.append(x['href'])
    
team_hrefs_list = list(set(team_hrefs_list))

In [8]:
#make sure there are 20 distinct teams
assert len(team_hrefs_list) == 20

# Step 2: Get all Player ID's + Season Cumulative Stats

In [9]:
#cumulative df for all players
season_cumulative_df = pd.DataFrame()

for short_url in team_hrefs_list:
    team_url = f"https://fbref.com{short_url}"
    print(team_url)

    #scrape all player hrefs and append to list
    response = requests.get(team_url)
    soup = BeautifulSoup(response.content, "html.parser")

    players_table = soup.find("table", id="stats_standard_9")
    team_df = pd.read_html(str(players_table))[0]
    team_df.columns = [col[1] for col in team_df.columns]

    team_df['team'] = short_url.split("/")[-1].replace('-Stats', '').replace('-', ' ')


    #add href column
    players_href = players_table.find_all('th', attrs = {'data-stat': 'player', 'scope':'row'})
    players_href_list = []
    for i in players_href:
        try:
            x = i.find('a', href=True)
            players_href_list.append(x['href'])
        except:
            print(i)

    players_href_list.append('') #add one for squad total row
    players_href_list.append('') #add one for squad total row

    team_df['player_link'] = players_href_list
            
    season_cumulative_df = season_cumulative_df.append(team_df, ignore_index=True)
    time.sleep(10)
   
#export to csv
season_cumulative_df.to_csv(f"{fpl_dir}/fb_ref_epl_2025_2026_cumulative_stats.csv", index=False)

https://fbref.com/en/squads/18bb7c10/Arsenal-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/fd962109/Fulham-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/822bd0ba/Liverpool-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/8602292d/Aston-Villa-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/8ef52968/Sunderland-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/19538871/Manchester-United-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/4ba7cbea/Bournemouth-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/943e8050/Burnley-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/d3fd31cc/Everton-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/e4a775cb/Nottingham-Forest-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/cd051869/Brentford-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>

In [10]:
season_cumulative_df.head(40)

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Gls,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,team,player_link
0,Gabriel Magalhães,br BRA,DF,27-285,6,6,540.0,6.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.5,0.5,0.0,0.5,5.0,26.0,1.0,0.17,0.00,0.17,0.17,0.17,0.08,0.00,0.08,0.08,0.08,Matches,Arsenal,/en/players/67ac5bb8/Gabriel-Magalhaes
1,David Raya,es ESP,GK,30-015,6,6,540.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.1,0.1,0.0,3.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.01,Matches,Arsenal,/en/players/98ea5115/David-Raya
2,Martín Zubimendi,es ESP,MF,26-240,6,6,532.0,5.9,2.0,0.0,2.0,2.0,0.0,0.0,1.0,0.0,0.3,0.3,0.5,0.8,4.0,27.0,6.0,0.34,0.00,0.34,0.34,0.34,0.05,0.09,0.14,0.05,0.14,Matches,Arsenal,/en/players/3ee0dd59/Martin-Zubimendi
3,Viktor Gyökeres,se SWE,FW,27-118,6,6,488.0,5.4,3.0,0.0,3.0,2.0,1.0,1.0,1.0,0.0,2.4,1.6,0.3,1.9,3.0,4.0,29.0,0.55,0.00,0.55,0.37,0.37,0.44,0.05,0.49,0.30,0.35,Matches,Arsenal,/en/players/4d5a9185/Viktor-Gyokeres
4,Riccardo Calafiori,it ITA,DF,23-134,6,6,454.0,5.0,1.0,2.0,3.0,1.0,0.0,0.0,3.0,0.0,1.7,1.7,0.5,2.2,13.0,21.0,22.0,0.20,0.40,0.59,0.20,0.59,0.33,0.10,0.43,0.33,0.43,Matches,Arsenal,/en/players/aded8e6f/Riccardo-Calafiori
5,Declan Rice,eng ENG,MF,26-259,6,5,465.0,5.2,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,1.1,1.2,12.0,31.0,8.0,0.00,0.39,0.39,0.00,0.39,0.03,0.21,0.24,0.03,0.24,Matches,Arsenal,/en/players/1c7012b8/Declan-Rice
6,Jurriën Timber,nl NED,DF,24-105,6,5,433.0,4.8,2.0,1.0,3.0,2.0,0.0,0.0,2.0,0.0,1.6,1.6,0.4,2.0,11.0,35.0,24.0,0.42,0.21,0.62,0.42,0.62,0.34,0.09,0.43,0.34,0.43,Matches,Arsenal,/en/players/41034650/Jurrien-Timber
7,William Saliba,fr FRA,DF,24-190,5,4,320.0,3.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.1,0.2,1.0,11.0,1.0,0.00,0.00,0.00,0.00,0.00,0.03,0.02,0.05,0.03,0.05,Matches,Arsenal,/en/players/972aeb2a/William-Saliba
8,Noni Madueke,eng ENG,FW,23-204,5,4,306.0,3.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3,0.3,0.8,1.1,18.0,9.0,44.0,0.00,0.00,0.00,0.00,0.00,0.09,0.25,0.34,0.09,0.34,Matches,Arsenal,/en/players/bf34eebd/Noni-Madueke
9,Bukayo Saka,eng ENG,FW,24-025,4,3,258.0,2.9,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.4,0.4,0.2,0.6,17.0,4.0,36.0,0.35,0.00,0.35,0.35,0.35,0.13,0.08,0.21,0.13,0.21,Matches,Arsenal,/en/players/bc7dc64d/Bukayo-Saka
10,Mikel Merino,es ESP,"MF,FW",29-100,5,3,232.0,2.6,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.2,0.2,0.1,0.3,5.0,9.0,8.0,0.39,0.00,0.39,0.39,0.39,0.07,0.04,0.11,0.07,0.11,Matches,Arsenal,/en/players/d080ed5e/Mikel-Merino
11,Martin Ødegaard,no NOR,MF,26-287,5,3,174.0,1.9,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.4,0.5,9.0,21.0,4.0,0.00,0.52,0.52,0.00,0.52,0.07,0.19,0.26,0.07,0.26,Matches,Arsenal,/en/players/79300479/Martin-Odegaard
12,Cristhian Mosquera,es ESP,DF,21-095,4,2,246.0,2.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Arsenal,/en/players/dc1ce4f5/Cristhian-Mosquera
13,Eberechi Eze,eng ENG,"FW,MF",27-093,4,2,234.0,2.6,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.6,0.6,0.7,1.3,8.0,14.0,16.0,0.00,0.77,0.77,0.00,0.77,0.22,0.27,0.49,0.22,0.49,Matches,Arsenal,/en/players/ae4fc6a4/Eberechi-Eze
14,Leandro Trossard,be BEL,FW,30-300,4,2,220.0,2.4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.5,0.5,0.2,0.7,4.0,6.0,19.0,0.00,0.41,0.41,0.00,0.41,0.21,0.09,0.30,0.21,0.30,Matches,Arsenal,/en/players/38ceb24a/Leandro-Trossard
15,Gabriel Martinelli,br BRA,FW,24-104,5,2,172.0,1.9,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.3,0.3,0.0,0.3,5.0,4.0,6.0,0.52,0.00,0.52,0.52,0.52,0.14,0.02,0.16,0.14,0.16,Matches,Arsenal,/en/players/48a5a5d6/Gabriel-Martinelli
16,Ben White,eng ENG,DF,27-357,1,1,71.0,0.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,1.0,4.0,0.0,0.00,0.00,0.00,0.00,0.00,0.02,0.06,0.07,0.02,0.07,Matches,Arsenal,/en/players/35e413f1/Ben-White
17,Ethan Nwaneri,eng ENG,MF,18-193,3,0,130.0,1.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.2,0.0,0.2,5.0,10.0,5.0,0.00,0.00,0.00,0.00,0.00,0.11,0.03,0.14,0.11,0.14,Matches,Arsenal,/en/players/7f94982c/Ethan-Nwaneri
18,Myles Lewis-Skelly,eng ENG,DF,19-004,4,0,68.0,0.8,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,5.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Arsenal,/en/players/5dff6c28/Myles-Lewis-Skelly
19,Kai Havertz,de GER,FW,26-111,1,0,30.0,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Arsenal,/en/players/fed7cb61/Kai-Havertz
20,Max Dowman,eng ENG,FW,15-273,2,0,27.0,0.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.0,0.1,4.0,0.0,6.0,0.00,0.00,0.00,0.00,0.00,0.43,0.00,0.43,0.43,0.43,Matches,Arsenal,/en/players/9008bb70/Max-Dowman
21,Andre Annous,eng ENG,FW,17-277,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Arsenal,/en/players/2d14071d/Andre-Annous
22,Kepa Arrizabalaga,es ESP,GK,30-362,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Arsenal,/en/players/28d596a0/Kepa-Arrizabalaga
23,Piero Hincapié,ec ECU,DF,23-264,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Arsenal,/en/players/0c7a48f8/Piero-Hincapie
24,Jakub Kiwior,pl POL,"DF,MF",25-227,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Arsenal,/en/players/dc3e663e/Jakub-Kiwior
25,Christian Nørgaard,dk DEN,MF,31-204,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Arsenal,/en/players/df0a4c90/Christian-Norgaard
26,Squad Total,NaN,NaN,26.0,6,66,540.0,6.0,12.0,9.0,21.0,11.0,1.0,1.0,9.0,0.0,9.1,8.3,5.4,13.7,129.0,247.0,243.0,2.00,1.50,3.50,1.83,3.33,1.52,0.90,2.42,1.39,2.29,NaN,Arsenal,
27,Opponent Total,NaN,NaN,26.6,6,66,540.0,6.0,3.0,2.0,5.0,3.0,0.0,0.0,10.0,0.0,3.9,3.9,3.4,7.3,92.0,152.0,151.0,0.50,0.33,0.83,0.50,0.83,0.65,0.56,1.21,0.65,1.21,NaN,Arsenal,
28,Jarrod Bowen,eng ENG,"FW,MF",28-284,6,6,540.0,6.0,3.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.8,0.8,0.9,1.7,21.0,13.0,47.0,0.50,0.00,0.50,0.50,0.50,0.14,0.14,0.28,0.14,0.28,Matches,West Ham United,/en/players/79c84d1c/Jarrod-Bowen
29,El Hadji Malick Diouf,sn SEN,DF,20-276,6,6,540.0,6.0,0.0,3.0,3.0,0.0,0.0,0.0,1.0,0.0,0.2,0.2,0.7,0.9,11.0,18.0,30.0,0.00,0.50,0.50,0.00,0.50,0.03,0.12,0.15,0.03,0.15,Matches,West Ham United,/en/players/bd5eb2e5/El-Hadji-Malick-Diouf
30,Max Kilman,eng ENG,DF,28-130,6,6,540.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.4,0.4,0.2,0.6,1.0,15.0,1.0,0.00,0.00,0.00,0.00,0.00,0.07,0.03,0.09,0.07,0.09,Matches,West Ham United,/en/players/d0f72bf1/Max-Kilman
31,Lucas Paquetá,br BRA,"MF,FW",28-034,6,6,518.0,5.8,2.0,0.0,2.0,1.0,1.0,1.0,1.0,0.0,1.5,0.7,0.4,1.1,3.0,43.0,24.0,0.35,0.00,0.35,0.17,0.17,0.26,0.07,0.33,0.13,0.20,Matches,West Ham United,/en/players/9b6f7fd5/Lucas-Paqueta
32,James Ward-Prowse,eng ENG,MF,30-333,5,5,416.0,4.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.9,1.0,1.0,20.0,8.0,0.00,0.00,0.00,0.00,0.00,0.03,0.20,0.23,0.03,0.23,Matches,West Ham United,/en/players/3515d404/James-Ward-Prowse
33,Kyle Walker-Peters,eng ENG,DF,28-170,5,4,380.0,4.2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.1,0.1,0.1,0.2,12.0,15.0,16.0,0.00,0.00,0.00,0.00,0.00,0.03,0.02,0.05,0.03,0.05,Matches,West Ham United,/en/players/984a5a64/Kyle-Walker-Peters
34,Mads Hermansen,dk DEN,GK,25-081,4,4,360.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,West Ham United,/en/players/c924b17d/Mads-Hermansen
35,Konstantinos Mavropanos,gr GRE,DF,27-293,4,4,360.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.4,0.4,0.0,0.4,2.0,17.0,0.0,0.00,0.00,0.00,0.00,0.00,0.10,0.00,0.10,0.10,0.10,Matches,West Ham United,/en/players/00963611/Konstantinos-Mavropanos
36,Niclas Füllkrug,de GER,FW,32-233,5,4,320.0,3.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.5,0.6,1.1,1.0,5.0,13.0,0.00,0.00,0.00,0.00,0.00,0.15,0.16,0.30,0.15,0.30,Matches,West Ham United,/en/players/4f16405e/Niclas-Fullkrug
37,Mateus Fernandes,pt POR,"MF,FW",21-082,4,4,311.0,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.5,0.6,5.0,11.0,6.0,0.00,0.00,0.00,0.00,0.00,0.03,0.16,0.19,0.03,0.19,Matches,West Ham United,/en/players/ef491564/Mateus-Fernandes
38,Tomáš Souček,cz CZE,MF,30-215,4,3,232.0,2.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.2,0.2,0.0,0.2,1.0,4.0,2.0,0.00,0.00,0.00,0.00,0.00,0.07,0.00,0.07,0.07,0.07,Matches,West Ham United,/en/players/6613c819/Tomas-Soucek
39,Crysencio Summerville,nl NED,"FW,MF",23-335,4,3,224.0,2.5,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.5,0.5,0.2,0.7,8.0,7.0,20.0,0.00,0.40,0.40,0.00,0.40,0.20,0.06,0.27,0.20,0.27,Matches,West Ham United,/en/players/df04eb4b/Crysencio-Summerville

# Step 3: Get Per Match Stats by Player

In [11]:
season_cumulative_df= pd.read_csv(f"{fpl_dir}/fb_ref_epl_2025_2026_cumulative_stats.csv")

season_cumulative_df.head()

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Matches,team,player_link
0,Gabriel Magalhães,br BRA,DF,27-285,6,6,540.0,6.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.5,0.5,0.0,0.5,5.0,26.0,1.0,0.17,0.0,0.17,0.17,0.17,0.08,0.00,0.08,0.08,0.08,Matches,Arsenal,/en/players/67ac5bb8/Gabriel-Magalhaes
1,David Raya,es ESP,GK,30-015,6,6,540.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.1,0.1,0.0,3.0,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.01,0.01,0.00,0.01,Matches,Arsenal,/en/players/98ea5115/David-Raya
2,Martín Zubimendi,es ESP,MF,26-240,6,6,532.0,5.9,2.0,0.0,2.0,2.0,0.0,0.0,1.0,0.0,0.3,0.3,0.5,0.8,4.0,27.0,6.0,0.34,0.0,0.34,0.34,0.34,0.05,0.09,0.14,0.05,0.14,Matches,Arsenal,/en/players/3ee0dd59/Martin-Zubimendi
3,Viktor Gyökeres,se SWE,FW,27-118,6,6,488.0,5.4,3.0,0.0,3.0,2.0,1.0,1.0,1.0,0.0,2.4,1.6,0.3,1.9,3.0,4.0,29.0,0.55,0.0,0.55,0.37,0.37,0.44,0.05,0.49,0.30,0.35,Matches,Arsenal,/en/players/4d5a9185/Viktor-Gyokeres
4,Riccardo Calafiori,it ITA,DF,23-134,6,6,454.0,5.0,1.0,2.0,3.0,1.0,0.0,0.0,3.0,0.0,1.7,1.7,0.5,2.2,13.0,21.0,22.0,0.20,0.4,0.59,0.20,0.59,0.33,0.10,0.43,0.33,0.43,Matches,Arsenal,/en/players/aded8e6f/Riccardo-Calafiori

In [12]:
def df_from_url(url):
    df = pd.read_html(url)[0]

    df.columns = [' '.join(col).strip() for col in df.columns]

    df = df.reset_index(drop=True)
    df.head()

    new_columns = []
    for col in df.columns:
        if 'level_0' in col:
          new_col = col.split()[-1] 
        else:
          new_col = col
        new_columns.append(new_col)

    df.columns = new_columns
    
    #drop nan rows
    df = df[df['Date'].notnull()]

    return df

In [13]:
player_urls = (
    season_cumulative_df
    .query('Min>0')
    .query('player_link != ""')
    .query('Player != "Squad Total"')
    .query('Player != "Opponent Total"')
    [['team', 'player_link']]
    .drop_duplicates()
    .to_dict(orient='index')
)

In [14]:
team_list = list(
    season_cumulative_df
    [['team']]
    .drop_duplicates()
    .team
)
team_list

['Arsenal',
 'West Ham United',
 'Crystal Palace',
 'Fulham',
 'Tottenham Hotspur',
 'Manchester City',
 'Liverpool',
 'Newcastle United',
 'Aston Villa',
 'Sunderland',
 'Leeds United',
 'Chelsea',
 'Manchester United',
 'Bournemouth',
 'Burnley',
 'Wolverhampton Wanderers',
 'Everton',
 'Brighton and Hove Albion',
 'Nottingham Forest',
 'Brentford']

In [15]:
#go team by team

In [27]:
team_list=[
 'Everton',
 'Brighton and Hove Albion',
 'Nottingham Forest',
 'Brentford']

In [28]:
for team in team_list:
    print(team)
    player_weekly_stats_by_team = pd.DataFrame()
    
    player_list = (
        season_cumulative_df
        .query(f'team=="{team}"')
        .query('Min>0')
        .query('player_link != ""')
        .query('Player != "Squad Total"')
        .query('Player != "Opponent Total"')
        [['player_link']]
        .drop_duplicates()
        .reset_index()
        .player_link
    )
    
    print(len(player_list))
    
    for player in player_list:
        player_name = player.split(sep="/")[-1]
        player_id = player.split(sep="/")[-2]
        
        print(f"   {player_name}")
        
        df_summary = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/summary/{player_name}-Match-Logs')
        time.sleep(6)
        df_passing = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/passing/{player_name}-Match-Logs')
        time.sleep(6)
        df_pass_types = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/passing_types/{player_name}-Match-Logs')
        time.sleep(6)
        df_shot_goal = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/gca/{player_name}-Match-Logs')
        time.sleep(6)
        df_posession = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/possession/{player_name}-Match-Logs')
        time.sleep(6)
        df_defensive_action = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/defense/{player_name}-Match-Logs')
        time.sleep(6)
        df_misc = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/misc/{player_name}-Match-Logs')
        time.sleep(6)
        
        df_all = (
            df_summary
            .merge(df_passing.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
            .merge(df_pass_types.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
            .merge(df_shot_goal.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
            .merge(df_posession.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
            .merge(df_defensive_action.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
            .merge(df_misc.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
        )
        
        df_all['team'] = team
        df_all['player_name'] = player_name
        df_all['player_id'] = player_id
        
        player_weekly_stats_by_team = pd.concat([player_weekly_stats_by_team, df_all], ignore_index=True)
        time.sleep(3)
        
    player_weekly_stats_by_team.to_csv(f"{fpl_dir}/{team} - Weekly Player Stats.csv", index=False)

Everton
17
   Kiernan-Dewsbury-Hall
   James-Garner
   Michael-Keane
   Jake-OBrien
   Jordan-Pickford
   James-Tarkowski
   Idrissa-Gana-Gueye
   Iliman-Ndiaye
   Jack-Grealish
   Beto
   Vitaliy-Mykolenko
   Tim-Iroegbunam
   Thierno-Barry
   Carlos-Alcaraz
   Merlin-Rohl
   Dwight-McNeil
   Tyler-Dibling
Brighton and Hove Albion
20
   Lewis-Dunk
   Jan-Paul-van-Hecke
   Bart-Verbruggen
   Kaoru-Mitoma
   Yankuba-Minteh
   Carlos-Baleba
   Yasin-Ayari
   Georginio-Rutter
   Joel-Veltman
   Maxim-De-Cuyper
   Danny-Welbeck
   Ferdi-Kadioglu
   Diego-Gomez
   Mats-Wieffer
   Matt-ORiley
   Jack-Hinshelwood
   Brajan-Gruda
   James-Milner
   Stefanos-Tzimas
   Diego-Coppola
Nottingham Forest
23
   Elliot-Anderson
   Nikola-Milenkovic
   Matz-Sels
   Neco-Williams
   Chris-Wood
   Dan-Ndoye
   Morgan-Gibbs-White
   Callum-Hudson-Odoi
   Ibrahim-Sangare
   Murillo
   Ola-Aina
   Morato
   Oleksandr-Zinchenko
   Dilane-Bakwa
   James-Mcatee
   Douglas-Luiz
   Nicolas-Dominguez
   Igor-Jesus
   Arnaud-Kalimuendo
   Nicolo-Savona
   Omari-Hutchinson
   Ryan-Yates
   Jota-Silva
Brentford
20
   Nathan-Collins
   Sepp-van-den-Berg
   Caoimhin-Kelleher
   Yehor-Yarmoliuk
   Michael-Kayode
   Thiago
   Kevin-Schade
   Jordan-Henderson
   Keane-Lewis-Potter
   Mikkel-Damsgaard
   Dango-Ouattara
   Ethan-Pinnock
   Mathias-Jensen
   Rico-Henry
   Aaron-Hickey
   Fabio-Carvalho
   Antoni-Milambo
   Frank-Onyeka
   Kristoffer-Ajer
   Vitaly-Janelt

In [29]:
x=2