In [24]:
import glob
from PIL import Image
import os
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import requests
import json
import time

from bs4 import BeautifulSoup

In [25]:

#display all columns (not just first and last 5)
pd.options.display.max_columns = None

In [26]:
# for traffic limit:
# https://www.sports-reference.com/bot-traffic.html

In [27]:
user_agent_list = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.2420.81',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 OPR/109.0.0.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 14.4; rv:124.0) Gecko/20100101 Firefox/124.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 OPR/109.0.0.0',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36',
    'Mozilla/5.0 (X11; Linux i686; rv:124.0) Gecko/20100101 Firefox/124.0',
]

In [28]:
headers = {
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
    'accept-language': 'en-US,en;q=0.9',
    'cache-control': 'max-age=0',
    #'if-modified-since': 'Thu, 22 May 2025 17:41:23 GMT',
    'priority': 'u=0, i',
#     'sec-ch-ua': '"Chromium";v="136", "Google Chrome";v="136", "Not.A/Brand";v="99"',
#     'sec-ch-ua-mobile': '?0',
#     'sec-ch-ua-platform': '"macOS"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'none',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
    # 'cookie': 'osano_consentmanager_uuid=ef80ee15-7ba1-4791-b7f2-865f9fe1c04c; _ga=GA1.1.1181001228.1745513799; _lc2_fpi=6fbc725567fc--01jsmbnqy8vjns34qjv841trve; _lc2_fpi_meta=%7B%22w%22%3A1745513799624%7D; _lr_env_src_ats=false; gamera_user_id=5af48dbf-cb2e-47b9-b2c4-1589b5c9046a; _cc_id=8c2dd72220b52c18ac50d5761d80a8f8; _sharedid=f1f0c558-d27f-460c-acba-6a279f2d6dd5; ccuid=7af0fbcb-c7c8-4e3b-a7dd-65f5557092f6; hubspotutk=a37a24785af3ff877ac47ba5d442e0a1; sr_lang_views-en=-0.5; sr_note_box_countdown=0; srcssfull=yes; is_live=true; _li_dcdm_c=.fbref.com; _sharedid_cst=9SzrLEgsPQ%3D%3D; hb_insticator_uid=2d837a14-b8e1-458e-a45b-ac46df6472b3; __qca=P1-23bef6ae-42c3-49f0-8f40-c41262b84fe5; pbjs_fabrickId=%7B%22fabrickId%22%3A%22E1%3AA1Rn-osazp14LkUI92JoX3tozWvc9GiPcd-uEuIQjTKgdq9K8xaD_Ja3wlh4NGMdyUJbfnc69T4wWDXPT7-NuF0LK1a9Vur-IJWK_vLJh48%22%7D; panoramaId_expiry=1748541760781; panoramaId=f0c938dd0a501317554515c9903a4945a70239d951ede15abcb9c97f2bdc1af9; panoramaIdType=panoIndiv; _lr_sampling_rate=100; __hssrc=1; sr_n=2%7CThu%2C%2022%20May%202025%2018%3A03%3A24%20GMT; __hstc=218152582.a37a24785af3ff877ac47ba5d442e0a1.1745513801734.1747936973589.1747943711872.4; _lr_retry_request=true; __cf_bm=GHv6JqUTD4Srt_9i9ZjZa2w4KJgnEv0JSj0GIhpOWPM-1747947424-1.0.1.1-_BH3H8Y35BtFtanAdUxCHAiNzZz6BQfvydtNIJwd23R1NcIxTT5mpc9sEFQn.3vJOY9Xf7Sgjn8H.QtsxtliFVWShpj.2pqfc1HtvWA.U4A; _ga_80FRT7VJ60=GS2.1.s1747943712$o5$g1$t1747947737$j0$l0$h0; _ga_T897NZ0GWZ=GS2.1.s1747943712$o5$g1$t1747947737$j0$l0$h0; cto_bidid=iFeFpV9VYUloYkF4YlZORVpYOHhoaVMwcjNBJTJCeHFwdlo1eERYaG1NNnlOSFglMkZVQnMyUGdHbGhCaHBEcDF5SSUyRlhzdjdCRnowRjQwOXlFNXJuNzZ2ciUyRjlzOUMyNFJKMzh1bXFiZUdPdzZDQmNaWm1DVVVHR1NYRng4aHVHbDNGMUliV3hIM29URU1ENnglMkJCVnJKSUpFJTJGZFRPMUElM0QlM0Q; __hssc=218152582.38.1747943711872; cto_bundle=jdqoEF9JeVB4dUVFNGIxdXRzJTJGd3JwdTElMkZkQTRNMHhUV05WUGdneEpYT3Q1Q0ZSV0ttbyUyQkRLQnRxb3pDU3V4dmlINyUyRnoxYTNRMiUyQk5qc2FIRFJwMU9ZdzF4NCUyQkxGbXdsbnlhNXhzejRBQ3BuUjdOMG1oYmk0NzlwNk4yR2VjR0JnVjRjMkFjNGVuc2NxM2duZCUyRkclMkJzV3Rjd0FYemtFb0VIRVZQclpqT0dwZGVxWGhhZUViQXdFVWYwaGEzb2Z1JTJCSVNJem9zVHowbWVITGJ6Zkp3RENKVzNUc1RNT1pyTDhRYTJuOWh0R1gzb0lNbzRZM0p6a1FpMGFsSUpXd2tCY1klMkIyUG1MN0I0WGVUQm5QejFBelU1cnhCNkoyTjZ6dG9xNllaM2JlQjZ0NUNsNlZiZ24xdjkxTTJDbEhvZHJ3anRFeENV; __gads=ID=1c580f67fe1263ae:T=1745513801:RT=1747947739:S=ALNI_MaBE8QPVcTxwnzu0LRWr89WWJoXiQ; __gpi=UID=0000109e519e38cb:T=1745513801:RT=1747947739:S=ALNI_MZY0HNGr161e1YwanVGVlUWbvL4Fg; __eoi=ID=5a6200b8b106bde6:T=1745513801:RT=1747947739:S=AA-AfjbtTQ054d4DRuJSOarDextj; pbjs_fabrickId_cst=riwMLDMsbg%3D%3D',
}

In [29]:
fpl_dir = '/Users/yuta/Desktop/fpl_web_scrape/2025-2026/FB Reference'

# Step 1: Get all EPL Teams

In [30]:
#start with premier league page
#get hrefs to all teams page to scrape player name and ids
url_epl_teams = 'https://fbref.com/en/comps/9/Premier-League-Stats'
response = requests.get(url_epl_teams, headers=headers)

soup = BeautifulSoup(response.content, "html.parser")

epl_teams_table = soup.find("table", id="results2025-202691_overall")
epl_teams_href = epl_teams_table.find_all('td', attrs = {'data-stat': 'team'})

team_hrefs_list = []
for i in epl_teams_href:
    x = i.find('a', href=True)
    team_hrefs_list.append(x['href'])
    
team_hrefs_list = list(set(team_hrefs_list))

In [31]:
#make sure there are 20 distinct teams
assert len(team_hrefs_list) == 20

# Step 2: Get all Player ID's + Season Cumulative Stats

In [32]:
#cumulative df for all players
season_cumulative_df = pd.DataFrame()

for short_url in team_hrefs_list:
    team_url = f"https://fbref.com{short_url}"
    print(team_url)

    #scrape all player hrefs and append to list
    response = requests.get(team_url)
    soup = BeautifulSoup(response.content, "html.parser")

    players_table = soup.find("table", id="stats_standard_9")
    team_df = pd.read_html(str(players_table))[0]
    team_df.columns = [col[1] for col in team_df.columns]

    team_df['team'] = short_url.split("/")[-1].replace('-Stats', '').replace('-', ' ')


    #add href column
    players_href = players_table.find_all('th', attrs = {'data-stat': 'player', 'scope':'row'})
    players_href_list = []
    for i in players_href:
        try:
            x = i.find('a', href=True)
            players_href_list.append(x['href'])
        except:
            print(i)

    players_href_list.append('') #add one for squad total row
    players_href_list.append('') #add one for squad total row

    team_df['player_link'] = players_href_list
            
    season_cumulative_df = season_cumulative_df.append(team_df, ignore_index=True)
    time.sleep(10)
   
#export to csv
season_cumulative_df.to_csv(f"{fpl_dir}/fb_ref_epl_2025_2026_cumulative_stats.csv", index=False)

https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/4ba7cbea/Bournemouth-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/8ef52968/Sunderland-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/8602292d/Aston-Villa-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/e4a775cb/Nottingham-Forest-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/d3fd31cc/Everton-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/943e8050/Burnley-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/18bb7c10/Arsenal-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/822bd0ba/Liverpool-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/19538871/Manchester-United-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/cd051869/Brentford-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/fd962109/Fulham-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>
https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats
<th class="left" data-stat="player" scope="row">Squad Total</th>
<th class="left" data-stat="player" scope="row">Opponent Total</th>

In [33]:
season_cumulative_df.head(40)

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Gls,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,team,player_link
0,Emmanuel Agbadou,ci CIV,DF,28-098,5,5,450.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.4,0.1,0.5,3.0,24.0,4.0,0.00,0.00,0.00,0.00,0.00,0.08,0.02,0.10,0.08,0.10,Matches,Wolverhampton Wanderers,/en/players/75f1ed80/Emmanuel-Agbadou
1,João Gomes,br BRA,MF,24-223,5,5,450.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.2,0.2,0.1,0.4,4.0,31.0,5.0,0.00,0.00,0.00,0.00,0.00,0.05,0.03,0.08,0.05,0.08,Matches,Wolverhampton Wanderers,/en/players/8b57ad2c/Joao-Gomes
2,Toti Gomes,pt POR,DF,26-250,5,5,389.0,4.3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.1,5.0,10.0,1.0,0.00,0.00,0.00,0.00,0.00,0.01,0.01,0.02,0.01,0.02,Matches,Wolverhampton Wanderers,/en/players/f0caab96/Toti-Gomes
3,José Sá,pt POR,GK,32-249,4,4,360.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.02,0.00,0.02,Matches,Wolverhampton Wanderers,/en/players/903b6e8b/Jose-Sa
4,Marshall Munetsi,zw ZIM,"FW,MF",29-093,5,3,340.0,3.8,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.5,0.5,0.4,1.0,3.0,6.0,9.0,0.00,0.26,0.26,0.00,0.26,0.14,0.11,0.25,0.14,0.25,Matches,Wolverhampton Wanderers,/en/players/2acf0cd7/Marshall-Munetsi
5,André,br BRA,MF,24-069,5,3,263.0,2.9,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,5.0,14.0,3.0,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.01,0.01,Matches,Wolverhampton Wanderers,/en/players/ec604e2c/Andre
6,Jean-Ricner Bellegarde,ht HAI,"MF,FW",27-088,5,3,214.0,2.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.3,0.4,6.0,14.0,5.0,0.00,0.00,0.00,0.00,0.00,0.05,0.13,0.18,0.05,0.18,Matches,Wolverhampton Wanderers,/en/players/10f0fdd3/Jean-Ricner-Bellegarde
7,Hugo Bueno,es ESP,"MF,DF",23-005,5,2,274.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.1,0.1,0.5,0.5,12.0,6.0,23.0,0.00,0.00,0.00,0.00,0.00,0.02,0.16,0.17,0.02,0.17,Matches,Wolverhampton Wanderers,/en/players/bfc3b3a0/Hugo-Bueno
8,Jackson Tchatchoua,cm CMR,"MF,DF",24-009,4,2,223.0,2.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,2.0,2.0,24.0,0.00,0.00,0.00,0.00,0.00,0.00,0.04,0.04,0.00,0.04,Matches,Wolverhampton Wanderers,/en/players/aeca7743/Jackson-Tchatchoua
9,Jørgen Strand Larsen,no NOR,FW,25-229,3,2,203.0,2.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.5,0.0,0.5,0.0,1.0,11.0,0.00,0.00,0.00,0.00,0.00,0.23,0.00,0.23,0.23,0.23,Matches,Wolverhampton Wanderers,/en/players/f553b2b3/Jorgen-Strand-Larsen
10,Jhon Arias,co COL,"FW,MF",28-002,5,2,180.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.2,0.1,0.3,4.0,8.0,7.0,0.00,0.00,0.00,0.00,0.00,0.11,0.05,0.16,0.11,0.16,Matches,Wolverhampton Wanderers,/en/players/86d96066/Jhon-Arias
11,Matt Doherty,ie IRL,DF,33-250,2,2,180.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Wolverhampton Wanderers,/en/players/d557d734/Matt-Doherty
12,Ladislav Krejčí,cz CZE,"MF,DF",26-156,2,2,180.0,2.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.7,0.7,0.1,0.8,0.0,7.0,3.0,0.50,0.00,0.50,0.50,0.50,0.34,0.04,0.38,0.34,0.38,Matches,Wolverhampton Wanderers,/en/players/5b5c2228/Ladislav-Krejci
13,Hwang Hee-chan,kr KOR,FW,29-240,4,2,173.0,1.9,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.6,0.6,0.0,0.6,1.0,0.0,5.0,0.52,0.00,0.52,0.52,0.52,0.29,0.02,0.31,0.29,0.31,Matches,Wolverhampton Wanderers,/en/players/169fd162/Hwang-Hee-chan
14,Rodrigo Gomes,pt POR,"DF,MF",22-078,4,2,166.0,1.8,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.7,0.7,0.1,0.7,3.0,2.0,15.0,0.54,0.00,0.54,0.54,0.54,0.36,0.04,0.40,0.36,0.40,Matches,Wolverhampton Wanderers,/en/players/8dcf77c0/Rodrigo-Gomes
15,Tolu Arokodare,ng NGA,FW,24-304,2,2,155.0,1.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.2,0.1,0.4,1.0,0.0,6.0,0.00,0.00,0.00,0.00,0.00,0.13,0.08,0.21,0.13,0.21,Matches,Wolverhampton Wanderers,/en/players/a42760bc/Tolu-Arokodare
16,Yerson Mosquera,co COL,DF,24-144,2,2,136.0,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.0,0.1,1.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.04,0.00,0.04,0.04,0.04,Matches,Wolverhampton Wanderers,/en/players/1e159d70/Yerson-Mosquera
17,David Møller Wolfe,no NOR,MF,23-153,3,2,131.0,1.5,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3,0.3,3.0,2.0,7.0,0.00,0.69,0.69,0.00,0.69,0.00,0.18,0.18,0.00,0.18,Matches,Wolverhampton Wanderers,/en/players/9affc5f2/David-Moller-Wolfe
18,Ki-Jana Hoever,nl NED,MF,23-248,2,2,106.0,1.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2,0.2,1.0,2.0,9.0,0.00,0.00,0.00,0.00,0.00,0.00,0.21,0.21,0.00,0.21,Matches,Wolverhampton Wanderers,/en/players/9a71e978/Ki-Jana-Hoever
19,Santiago Bueno,uy URU,DF,26-318,2,1,125.0,1.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.02,0.02,0.00,0.02,Matches,Wolverhampton Wanderers,/en/players/edc98fac/Santiago-Bueno
20,Fer López,es ESP,"MF,FW",21-122,4,1,105.0,1.2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.1,0.1,0.7,0.9,4.0,13.0,9.0,0.00,0.86,0.86,0.00,0.86,0.10,0.64,0.74,0.10,0.74,Matches,Wolverhampton Wanderers,/en/players/675cacff/Fer-Lopez
21,Sam Johnstone,eng ENG,GK,32-182,1,1,90.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Wolverhampton Wanderers,/en/players/9e5708be/Sam-Johnstone
22,Sasa Kalajdzic,at AUT,FW,28-078,1,0,15.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Wolverhampton Wanderers,/en/players/15f24fe7/Sasa-Kalajdzic
23,Daniel Bentley,eng ENG,GK,32-072,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Matches,Wolverhampton Wanderers,/en/players/68db6358/Daniel-Bentley
24,Squad Total,NaN,NaN,26.8,5,55,450.0,5.0,3.0,3.0,6.0,3.0,0.0,0.0,10.0,1.0,4.4,4.4,3.4,7.8,58.0,151.0,149.0,0.60,0.60,1.20,0.60,1.20,0.88,0.68,1.56,0.88,1.56,NaN,Wolverhampton Wanderers,
25,Opponent Total,NaN,NaN,27.4,5,55,450.0,5.0,12.0,9.0,21.0,12.0,0.0,0.0,7.0,0.0,7.7,7.7,6.8,14.5,76.0,207.0,206.0,2.40,1.80,4.20,2.40,4.20,1.53,1.36,2.90,1.53,2.90,NaN,Wolverhampton Wanderers,
26,Tijjani Reijnders,nl NED,MF,27-056,5,5,450.0,5.0,1.0,2.0,3.0,1.0,0.0,0.0,1.0,0.0,0.7,0.7,1.0,1.7,12.0,18.0,20.0,0.20,0.40,0.60,0.20,0.60,0.15,0.19,0.34,0.15,0.34,Matches,Manchester City,/en/players/afb61630/Tijjani-Reijnders
27,Erling Haaland,no NOR,FW,25-064,5,5,413.0,4.6,6.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,6.3,6.3,0.9,7.2,9.0,4.0,14.0,1.31,0.00,1.31,1.31,1.31,1.37,0.19,1.56,1.37,1.56,Matches,Manchester City,/en/players/1f44ac21/Erling-Haaland
28,Rúben Dias,pt POR,DF,28-132,5,4,366.0,4.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,11.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Manchester City,/en/players/31c69ef1/Ruben-Dias
29,Bernardo Silva,pt POR,MF,31-044,5,4,350.0,3.9,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.1,0.1,1.7,1.7,7.0,15.0,20.0,0.00,0.26,0.26,0.00,0.26,0.01,0.43,0.45,0.01,0.45,Matches,Manchester City,/en/players/3eb22ec9/Bernardo-Silva
30,Jeremy Doku,be BEL,"MF,FW",23-119,5,3,283.0,3.1,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.2,0.2,1.9,2.1,22.0,4.0,25.0,0.00,0.64,0.64,0.00,0.64,0.07,0.60,0.67,0.07,0.67,Matches,Manchester City,/en/players/fffea3e5/Jeremy-Doku
31,Rodri,es ESP,MF,29-093,4,3,271.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.1,0.2,4.0,19.0,5.0,0.00,0.00,0.00,0.00,0.00,0.05,0.03,0.07,0.05,0.07,Matches,Manchester City,/en/players/6434f10d/Rodri
32,James Trafford,eng ENG,GK,22-348,3,3,270.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Manchester City,/en/players/259fea27/James-Trafford
33,John Stones,eng ENG,DF,31-118,4,3,265.0,2.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,14.0,2.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Manchester City,/en/players/5eecec3d/John-Stones
34,Oscar Bobb,no NOR,"FW,MF",22-073,4,3,258.0,2.9,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.3,0.3,0.4,0.7,10.0,10.0,33.0,0.00,0.35,0.35,0.00,0.35,0.10,0.13,0.23,0.10,0.23,Matches,Manchester City,/en/players/eed2427e/Oscar-Bobb
35,Abdukodir Khusanov,uz UZB,DF,21-206,4,3,228.0,2.5,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,4.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Manchester City,/en/players/d17ce930/Abdukodir-Khusanov
36,Rayan Aït-Nouri,dz ALG,DF,24-109,3,3,202.0,2.2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.2,0.2,6.0,7.0,8.0,0.00,0.00,0.00,0.00,0.00,0.02,0.09,0.11,0.02,0.11,Matches,Manchester City,/en/players/9b398aea/Rayan-Ait-Nouri
37,Nico O’Reilly,eng ENG,"DF,MF",20-186,4,2,220.0,2.4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.1,0.1,0.0,0.1,3.0,5.0,5.0,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.03,0.03,0.03,Matches,Manchester City,/en/players/91ca4a16/Nico-OReilly
38,Nicolás González,es ESP,MF,23-263,4,2,194.0,2.2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.1,0.1,0.0,0.1,3.0,17.0,5.0,0.00,0.00,0.00,0.00,0.00,0.02,0.00,0.02,0.02,0.02,Matches,Manchester City,/en/players/2c56a792/Nicolas-Gonzalez
39,Gianluigi Donnarumma,it ITA,GK,26-210,2,2,180.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,Manchester City,/en/players/08f5afaa/Gianluigi-Donnarumma

# Step 3: Get Per Match Stats by Player

In [34]:
season_cumulative_df= pd.read_csv(f"{fpl_dir}/fb_ref_epl_2025_2026_cumulative_stats.csv")

season_cumulative_df.head()

,Player,Nation,Pos,Age,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,xG.1,xAG.1,xG+xAG,npxG.1,npxG+xAG.1,Matches,team,player_link
0,Emmanuel Agbadou,ci CIV,DF,28-098,5,5,450.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.4,0.1,0.5,3.0,24.0,4.0,0.0,0.00,0.00,0.0,0.00,0.08,0.02,0.10,0.08,0.10,Matches,Wolverhampton Wanderers,/en/players/75f1ed80/Emmanuel-Agbadou
1,João Gomes,br BRA,MF,24-223,5,5,450.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.2,0.2,0.1,0.4,4.0,31.0,5.0,0.0,0.00,0.00,0.0,0.00,0.05,0.03,0.08,0.05,0.08,Matches,Wolverhampton Wanderers,/en/players/8b57ad2c/Joao-Gomes
2,Toti Gomes,pt POR,DF,26-250,5,5,389.0,4.3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.1,5.0,10.0,1.0,0.0,0.00,0.00,0.0,0.00,0.01,0.01,0.02,0.01,0.02,Matches,Wolverhampton Wanderers,/en/players/f0caab96/Toti-Gomes
3,José Sá,pt POR,GK,32-249,4,4,360.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00,0.02,0.02,0.00,0.02,Matches,Wolverhampton Wanderers,/en/players/903b6e8b/Jose-Sa
4,Marshall Munetsi,zw ZIM,"FW,MF",29-093,5,3,340.0,3.8,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.5,0.5,0.4,1.0,3.0,6.0,9.0,0.0,0.26,0.26,0.0,0.26,0.14,0.11,0.25,0.14,0.25,Matches,Wolverhampton Wanderers,/en/players/2acf0cd7/Marshall-Munetsi

In [35]:
def df_from_url(url):
    df = pd.read_html(url)[0]

    df.columns = [' '.join(col).strip() for col in df.columns]

    df = df.reset_index(drop=True)
    df.head()

    new_columns = []
    for col in df.columns:
        if 'level_0' in col:
          new_col = col.split()[-1] 
        else:
          new_col = col
        new_columns.append(new_col)

    df.columns = new_columns
    
    #drop nan rows
    df = df[df['Date'].notnull()]

    return df

In [36]:
player_urls = (
    season_cumulative_df
    .query('Min>0')
    .query('player_link != ""')
    .query('Player != "Squad Total"')
    .query('Player != "Opponent Total"')
    [['team', 'player_link']]
    .drop_duplicates()
    .to_dict(orient='index')
)

In [43]:
team_list = list(
    season_cumulative_df
    [['team']]
    .drop_duplicates()
    .team
)
team_list

['Wolverhampton Wanderers',
 'Manchester City',
 'Brighton and Hove Albion',
 'Bournemouth',
 'Sunderland',
 'Newcastle United',
 'Aston Villa',
 'Crystal Palace',
 'West Ham United',
 'Nottingham Forest',
 'Everton',
 'Burnley',
 'Tottenham Hotspur',
 'Arsenal',
 'Liverpool',
 'Chelsea',
 'Manchester United',
 'Brentford',
 'Fulham',
 'Leeds United']

In [38]:
#go team by team

In [48]:
team_list = [

 'Leeds United'
]

In [49]:
for team in team_list:
    print(team)
    player_weekly_stats_by_team = pd.DataFrame()
    
    player_list = (
        season_cumulative_df
        .query(f'team=="{team}"')
        .query('Min>0')
        .query('player_link != ""')
        .query('Player != "Squad Total"')
        .query('Player != "Opponent Total"')
        [['player_link']]
        .drop_duplicates()
        .reset_index()
        .player_link
    )
    
    print(len(player_list))
    
    for player in player_list:
        player_name = player.split(sep="/")[-1]
        player_id = player.split(sep="/")[-2]
        
        print(f"   {player_name}")
        
        df_summary = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/summary/{player_name}-Match-Logs')
        time.sleep(6)
        df_passing = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/passing/{player_name}-Match-Logs')
        time.sleep(6)
        df_pass_types = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/passing_types/{player_name}-Match-Logs')
        time.sleep(6)
        df_shot_goal = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/gca/{player_name}-Match-Logs')
        time.sleep(6)
        df_posession = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/possession/{player_name}-Match-Logs')
        time.sleep(6)
        df_defensive_action = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/defense/{player_name}-Match-Logs')
        time.sleep(6)
        df_misc = df_from_url(f'https://fbref.com/en/players/{player_id}/matchlogs/2025-2026/c9/misc/{player_name}-Match-Logs')
        time.sleep(6)
        
        df_all = (
            df_summary
            .merge(df_passing.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
            .merge(df_pass_types.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
            .merge(df_shot_goal.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
            .merge(df_posession.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
            .merge(df_defensive_action.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
            .merge(df_misc.drop('Report', axis=1), on=['Date', 'Day', 'Round', 'Venue', 'Result', 'Squad', 'Opponent', 'Start', 'Pos', 'Min'], how='outer')
        )
        
        df_all['team'] = team
        df_all['player_name'] = player_name
        df_all['player_id'] = player_id
        
        player_weekly_stats_by_team = pd.concat([player_weekly_stats_by_team, df_all], ignore_index=True)
        time.sleep(3)
        
    player_weekly_stats_by_team.to_csv(f"{fpl_dir}/{team} - Weekly Player Stats.csv", index=False)

Leeds United
21
   Joe-Rodon
   Anton-Stach
   Pascal-Struijk
   Gabriel-Gudmundsson
   Jayden-Bogle
   Sean-Longstaff
   Lucas-Perri
   Ethan-Ampadu
   Daniel-James
   Wilfried-Gnonto
   Brenden-Aaronson
   Ilia-Gruev
   Karl-Darlow
   Dominic-Calvert-Lewin
   Noah-Okafor
   Ao-Tanaka
   Joel-Piroe
   Lukas-Nmecha
   Jack-Harrison
   James-Justin
   Sam-Byram

In [ ]:
x=2