In [1]:
import glob
from PIL import Image
import os
import pandas as pd
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import requests
import json

In [2]:
#display all columns (not just first and last 5)
pd.options.display.max_columns = None

In [3]:
data = requests.get('https://fantasy.premierleague.com/api/bootstrap-static/')
data = json.loads(data.content)

for key in data:
    print (key)

chips
events
game_settings
game_config
phases
teams
total_players
element_stats
element_types
elements

# Teams

In [4]:
len(data['teams'])

20

In [5]:
team_df = pd.DataFrame(data['teams'])
team_df.head()

,code,draw,form,id,loss,name,played,points,position,short_name,strength,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,0,ARS,4,None,False,0,1320,1325,1350,1350,1290,1300,1
1,7,0,None,2,0,Aston Villa,0,0,0,AVL,3,None,False,0,1125,1250,1110,1200,1140,1300,2
2,90,0,None,3,0,Burnley,0,0,0,BUR,2,None,False,0,1050,1050,1050,1050,1050,1050,43
3,91,0,None,4,0,Bournemouth,0,0,0,BOU,3,None,False,0,1150,1180,1100,1160,1200,1200,127
4,94,0,None,5,0,Brentford,0,0,0,BRE,3,None,False,0,1120,1185,1080,1080,1160,1290,130

# Players Season Cumulative Stats

In [7]:
player_season_df = pd.DataFrame(data['elements'])
player_season_df.sort_values('minutes', ascending=False).head()

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,removed,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,region,team_join_date,birth_date,has_temporary_code,opta_code,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,defensive_contribution,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,expected_goals_per_90,saves_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,goals_conceded_per_90,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90
0,True,True,NaN,None,154561,0,0,0,0,0,1,4.5,None,0,David,0.0,1,False,,None,55,154561.jpg,3.7,False,Raya Martín,18.3,False,None,a,1,3,142,0,0,0,0,0.0,25.8,Raya,200.0,2024-07-04,1995-09-15,False,p154561,3420,0,0,13,34,0,0,0,3,0,86,10,555,755.4,10.7,0.0,76.7,0,38,0.00,0.03,0.03,35.03,37,8,342,11,636,77,178,8,NaN,,NaN,,NaN,,0.00,2.26,0.00,0.00,0.92,0.89,127,4,477,77,68,11,19,2,1.0,0.34
144,True,True,NaN,None,432830,0,0,0,0,0,2,2.6,None,0,Nathan,0.0,106,False,,None,50,432830.jpg,3.3,False,Collins,1.6,False,None,a,5,94,127,0,0,0,0,0.0,25.4,Collins,104.0,2023-07-04,2001-04-30,False,p432830,3420,2,7,8,57,0,0,0,5,0,0,11,549,1023.2,160.5,311.0,149.6,351,38,2.44,1.57,4.01,56.31,6,1,199,53,96,8,72,8,NaN,,NaN,,NaN,,0.06,0.00,0.04,0.10,1.48,1.50,287,50,401,181,109,25,151,54,1.0,0.21
253,True,True,NaN,None,172649,0,0,0,0,0,1,2.6,None,0,Dean,0.0,253,False,,None,50,172649.jpg,3.6,False,Henderson,3.4,False,None,a,8,31,135,0,0,0,0,0.0,27.0,Henderson,241.0,2023-08-31,1997-03-12,False,p172649,3420,0,0,11,51,0,1,0,3,0,104,8,466,853.6,30.0,4.0,88.6,0,38,0.01,0.02,0.03,50.33,17,4,308,3,336,2,147,4,NaN,,NaN,,NaN,,0.00,2.74,0.00,0.00,1.32,1.34,237,10,351,68,74,13,94,17,1.0,0.29
287,True,True,NaN,None,111234,0,0,0,0,0,1,4.5,None,0,Jordan,0.0,287,False,,None,55,111234.jpg,4.2,False,Pickford,12.4,False,None,a,9,11,158,0,0,0,0,0.0,28.7,Pickford,241.0,2017-07-01,1994-03-07,False,p111234,3420,0,1,12,44,0,2,0,7,0,122,15,593,1052.0,20.3,0.0,107.0,0,38,0.00,0.22,0.22,46.11,4,1,322,4,632,74,124,1,NaN,,NaN,,NaN,,0.00,3.21,0.01,0.01,1.21,1.16,118,1,468,74,31,6,36,5,1.0,0.32
315,True,True,NaN,None,80201,0,0,0,0,0,1,3.1,None,0,Bernd,0.0,314,False,,None,50,80201.jpg,3.0,False,Leno,1.7,False,None,a,10,54,115,0,0,0,0,0.0,23.0,Leno,80.0,2022-08-02,1992-03-04,False,p80201,3420,0,2,5,54,0,1,0,5,0,110,5,475,967.0,20.0,0.0,98.6,0,38,0.00,0.03,0.03,47.75,8,2,324,6,576,64,130,2,NaN,,NaN,,NaN,,0.00,2.89,0.00,0.00,1.26,1.42,215,5,329,63,132,19,145,21,1.0,0.13

In [8]:
#get list of IDs to scrape by GW stats per player
player_id_list = list(player_season_df[['id']].drop_duplicates().id)
assert len(player_id_list)== len(player_season_df)

# Players By Gameweek Stats

In [8]:
player_weekly_df = pd.DataFrame()

for pid in player_id_list:
    #print(pid)
    response = requests.get(f'https://fantasy.premierleague.com/api/element-summary/{pid}/')
    
    if response.status_code != 200:
        raise Exception("Response was code " + str(response.status_code))
        print(pid)
        
    p_data = pd.DataFrame(response.json()['history'])
    p_data['id'] = pid
    player_weekly_df = player_weekly_df.append(p_data)

In [9]:
assert len(player_weekly_df[['element']].drop_duplicates())== len(player_season_df)

In [10]:
#merge on player name and team name to player_weekly_df
player_names = player_season_df[['id', 'team', 'element_type', 'first_name', 'second_name', 'web_name']].drop_duplicates()
team_names = team_df[['id', 'name', 'short_name']].drop_duplicates().rename(columns={'id':'team'})
opponent_names = team_df[['id', 'name', 'short_name']].drop_duplicates().rename(columns={'id':'opponent_id', 'name':'opponent', 'short_name':'opponent_short_name'})


player_weekly_with_deets = (
    player_weekly_df
    .merge(player_names, left_on='id', right_on='id', how='left')
    .merge(team_names, left_on='team', right_on='team', how='left')
    .merge(opponent_names, left_on='opponent_team', right_on='opponent_id', how='left')
    .rename(columns={
        'team' : 'team_id',
        'name' : 'team'
    })
)

for var in [
    'influence', 'creativity', 'threat', 'ict_index', 'starts', 
    'expected_goals', 'expected_assists', 'expected_goal_involvements',
    'expected_goals_conceded'
]:
    player_weekly_with_deets[var] = player_weekly_with_deets[var].astype(float)

player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 1), 'position'] = 'GK'
player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 2), 'position'] = 'DEF'
player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 3), 'position'] = 'MID'
player_weekly_with_deets.loc[(player_weekly_with_deets['element_type'] == 4), 'position'] = 'FWD'

In [11]:
player_weekly_with_deets.head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,mng_win,mng_draw,mng_loss,mng_underdog_win,mng_underdog_draw,mng_clean_sheets,mng_goals_scored,value,transfers_balance,selected,transfers_in,transfers_out,id,team_id,element_type,first_name,second_name,web_name,team,short_name,opponent_id,opponent,opponent_short_name,position
0,1,2,20,0,True,2024-08-17T14:00:00Z,2,0,1,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,55,0,2923,0,0,1,1,3,Fábio,Ferreira Vieira,Fábio Vieira,Arsenal,ARS,20,Wolves,WOL,MID
1,1,11,2,0,False,2024-08-24T16:30:00Z,0,2,2,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,55,-790,2321,84,874,1,1,3,Fábio,Ferreira Vieira,Fábio Vieira,Arsenal,ARS,2,Aston Villa,AVL,MID
2,1,21,5,0,True,2024-08-31T11:30:00Z,1,1,3,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,54,-279,2397,355,634,1,1,3,Fábio,Ferreira Vieira,Fábio Vieira,Arsenal,ARS,5,Brighton,BHA,MID
3,1,39,18,0,False,2024-09-15T13:00:00Z,0,1,4,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,54,-747,1650,0,747,1,1,3,Fábio,Ferreira Vieira,Fábio Vieira,Arsenal,ARS,18,Spurs,TOT,MID
4,1,47,13,0,False,2024-09-22T15:30:00Z,2,2,5,False,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0,0,0,54,-174,1494,0,174,1,1,3,Fábio,Ferreira Vieira,Fábio Vieira,Arsenal,ARS,13,Man City,MCI,MID

# Fixtures

In [9]:
response = requests.get("https://fantasy.premierleague.com/api/fixtures/")
fixtures_df = pd.DataFrame(response.json())
fixtures_df.head()

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2561895,1,False,False,1,2025-08-15T19:00:00Z,0,False,False,4,None,12,None,[],3,5,124791
1,2561896,1,False,False,2,2025-08-16T11:30:00Z,0,False,False,15,None,2,None,[],3,4,124792
2,2561897,1,False,False,3,2025-08-16T14:00:00Z,0,False,False,10,None,6,None,[],3,3,124793
3,2561900,1,False,False,6,2025-08-16T14:00:00Z,0,False,False,3,None,18,None,[],2,3,124796
4,2561899,1,False,False,5,2025-08-16T14:00:00Z,0,False,False,19,None,17,None,[],2,2,124795

# Export

In [13]:
#export to CSV
fpl_dir = '/Users/yuta/Desktop/fpl_web_scrape/2024-2025'

team_df.to_csv(f"{fpl_dir}/teams.csv", index=False)
fixtures_df.to_csv(f"{fpl_dir}/fixtures.csv", index=False)
player_season_df.to_csv(f"{fpl_dir}/player_season_stats.csv", index=False)
#player_weekly_df.to_csv(f"{fpl_dir}/data/player_weekly_stats.csv", index=False)
player_weekly_with_deets.to_csv(f"{fpl_dir}/player_weekly_stats.csv", index=False)